CONTRIBUTING.md
LICENSE
README.md

- Update readme
- Add contributing guide
- Add license

Update GitHub repo

---

GenderPayGap.WebJob/Functions/Functions.SendReminderEmails.cs

- Added additional try/catch block so that a record is only saved in DB if email is successfully sent first
- Swapped `DateTime.Now` for `VirtualDateTime.Now`
- Added another field for the Notify email

#37486 send reminder emails

---

GenderPayGap.Core/Enums.cs
GenderPayGap.WebUI/Controllers/Admin/AdminUserContactPreferencesController.cs
GenderPayGap.WebUI/Models/Admin/AdminResendVerificationEmailViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminUserResendVerificationEmailController.cs
GenderPayGap.WebUI/Views/Admin/ViewUser.cshtml
GenderPayGap.WebUI/Views/AdminUserResendVerificationEmail/ResendVerificationEmail.cshtml
GenderPayGap.WebUI/Views/AdminUserResendVerificationEmail/VerificationEmailSent.cshtml
GenderPayGap.sln.DotSettings

Allow admin users to re-send "verify your email address" emails.
This is the email that users receive when they first sign up.
Perhaps their corporate spam filter blocked the initial email, or they deleted it.
This will allow the admins to re-send that email.

#38905 Re-send verification email

---

GenderPayGap.WebUI/Views/Register/AddAddress.cshtml

Updates the form from this 
to this 
I have followed the multiple text inputs GDS pattern from [here](https://design-system.service.gov.uk/patterns/addresses/)

AB#39340 Update address form

---

GenderPayGap.WebJob/Classes/Messenger.cs
GenderPayGap.WebJob/Functions/Functions .CheckSiteCert.cs
GenderPayGap.WebJob/Functions/Functions.ExecuteWebJob.cs
GenderPayGap.WebJob/Functions/Functions.FetchCompaniesHouseData.cs
GenderPayGap.WebJob/Functions/Functions.Logging.cs
GenderPayGap.WebJob/Functions/Functions.MergeLogs.cs
GenderPayGap.WebJob/Functions/Functions.Purge.cs
GenderPayGap.WebJob/Functions/Functions.Scope.cs
GenderPayGap.WebJob/Functions/Functions.Search.cs
GenderPayGap.WebJob/Functions/Functions.SendEmail.cs
GenderPayGap.WebJob/Functions/Functions.SendNotifyEmail.cs
GenderPayGap.WebJob/Functions/Functions.SendReminderEmails.cs
GenderPayGap.WebJob/Functions/Functions.StorageSnapshots.cs
GenderPayGap.WebJob/Functions/Functions.cs

Add logging to webjob functions

AB#39359 log web job runs

---

GenderPayGap.WebUI/Controllers/Admin/AdminDatabaseIntegrityChecksController.cs
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ActiveOrganisationsWithTheSameCompanyNumber.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ActiveOrganisationsWithTheSameName.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/DatabaseIntegrityChecks.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWhereLatestAddressIsNotActive.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveAddresses.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveReturnsForASingleYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveScopesForASingleYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithNoActiveScopeForEveryYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PrivateSectorOrganisationsWithAPublicSectorType.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PublicSectorOrganisationsWithoutAPublicSectorType.cshtml

The AJAX requests were taking too long, but running each request individually is fine. So we have split each request in to a separate page.

#39114 restructure database integrity checks page

---

GenderPayGap.WebUI/Models/Admin/AdminSearchViewModel.cs
GenderPayGap.WebUI/Services/AdminSearchService.cs
GenderPayGap.WebUI/Views/Admin/Search.cshtml

Also show organisation status on admin search page (for non-active orgs)
See screenshot: https://agilefactory.visualstudio.com/GenderPayGapLive/_workitems/edit/39493

#39493 Also show organisation status on admin search page (for non-active orgs)

---

GenderPayGap.WebUI/Views/ReportingStepByStep/ReportingSteps.cshtml

Update to copy on step 4 of the step by step prototype

Update prototype copy

---

GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs

Change column name for scope admin download

AB#39493 Fix organisation size column name

---

GenderPayGap.WebUI/Views/ReportingStepByStep/ReportingSteps.cshtml

Update copy on steps 5 and 6 of step by step prototype

Update prototype copy for reporting steps

---

GenderPayGap.WebUI/Controllers/Account/AccountCreationController.cs

Previous code didn't persist update to DB

#39722 Save user after verification

---

GenderPayGap.WebUI/Views/AdminOrganisationName/ManuallyChangeOrganisationName.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/CharacterCount.cshtml
GovUkDesignSystem/HtmlGenerators/CharacterCountHtmlGenerator.cs
GovUkDesignSystem/HtmlGenerators/TextAreaHtmlGenerator.cs
GovUkDesignSystem/HtmlGenerators/TextInputHtmlGenerator.cs

Update TextAreaHtmlGenerator to include `label.for` value
Also updates TextInputHtmlGenerator and CharacterCountHtmlGenerator to make them more consistent

AB#39790 unlabelled textarea

---

GenderPayGap.WebUI/Controllers/Admin/AdminDatabaseIntegrityChecksController.cs
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ActiveOrganisationsWithTheSameCompanyNumber.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ActiveOrganisationsWithTheSameName.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/DatabaseIntegrityChecks.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveAddresses.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveReturnsForASingleYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveScopesForASingleYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithNoActiveScopeForEveryYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithoutAnActiveAddress.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PrivateSectorOrganisationsWithAPublicSectorType.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PublicSectorOrganisationsWithoutAPublicSectorType.cshtml

Adds descriptions for the database integrity checks. It also adds one new check for organisations without an active address.

AB#39941 descriptions for db checks

---

GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationReturnController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminViewOrganisationController.cs
GenderPayGap.WebUI/Helpers/CsvDownloadHelper.cs
GenderPayGap.WebUI/Models/Admin/AdminOrganisationReturnDetailsViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminViewOrganisationViewModel.cs
GenderPayGap.WebUI/Views/Admin/ViewOrganisation.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturnDetails.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturns.cshtml

It's less hideous than last time!

AB#38814 Admin page to see full history of return details (including all the figures)

---

GenderPayGap.Core/FeatureFlagHelper.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/RegistrationTests.Manual.cs
GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
GenderPayGap.WebUI/appsettings.LOCAL.json
GenderPayGap.WebUI/appsettings.json

This is a basic working solution and I'm pushing it here to start a conversation. In particular, if I am working at the right level of abstraction or making the changes in the right places.
- new private org
- existing private org
- non-UK private org
- public org

AB#40244 WIP MVP

---

GenderPayGap.Core/FeatureFlagHelper.cs
GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
GenderPayGap.WebUI/appsettings.LOCAL.json
GenderPayGap.WebUI/appsettings.json

Adds a feature flag for registration review emails

AB#40328 Switch off registration review emails

---

GenderPayGap.IdentityServer4/Views/Account/Login.cshtml
GenderPayGap.IdentityServer4/Views/Shared/CovidMessage.cshtml
GenderPayGap.IdentityServer4/Views/Shared/_Layout.cshtml
GenderPayGap.IdentityServer4/wwwroot/public/assets/application/stylesheets/covid-message-v1.css
GenderPayGap.WebUI/Views/Components/CovidMessage.cshtml
GenderPayGap.WebUI/Views/Organisation/ManageOrganisation.cshtml
GenderPayGap.WebUI/Views/Organisation/ManageOrganisations.cshtml
GenderPayGap.WebUI/Views/Register/ChooseOrganisation.cshtml
GenderPayGap.WebUI/Views/Submit/CheckData.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Report.cshtml
GenderPayGap.WebUI/Views/Viewing/Finder/SearchResults.cshtml
GenderPayGap.WebUI/Views/Viewing/Launchpad/Index.cshtml
GenderPayGap.WebUI/wwwroot/styles/_gender-pay-gap-custom.scss
GenderPayGap.WebUI/wwwroot/styles/components/_covid-message.scss

Add COVID-19 messaging to various pages

#40233 remove deadline enforcement actions

---

GenderPayGap.Database.Models/Extensions/Return.cs
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml

Previous PR covered case where a submission was changed after the deadline, but didn't cover case where no submission was present.

AB#40376 Late flag bug fix

---

GenderPayGap.WebJob/Functions/Functions .CheckSiteCert.cs
GenderPayGap.WebJob/Functions/Functions.MergeLogs.cs
GenderPayGap.WebJob/Functions/Functions.Purge.cs
GenderPayGap.WebJob/Functions/Functions.Scope.cs
GenderPayGap.WebJob/Functions/Functions.Search.cs
GenderPayGap.WebJob/Functions/Functions.StorageSnapshots.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateDownloads.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateOrganisationLateSubmissions.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateOrganisations.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateOrphanOrganisations.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateRegistrationAddresses.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateRegistrations.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateScopes.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateSubmissions.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateUnverifiedRegistrations.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateUsers.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateUsersToContactForFeedback.cs
GenderPayGap.WebJob/Functions/UpdateFiles/Functions.UpdateUsersToSendInfo.cs

- Webjob errors in PurgeUser function caused by FK constraint. Unable to delete user because they had audit logs in the DB.
- Updated function deletes the logs first
- I have refactored the function so that if one user fails, the others are still processed
- I have also set up Azure alerts to notify the team DL when functions fail (for all environments)

AB#40181 fix webjob errors

---

GenderPayGap.WebUI/Views/Admin/Downloads.cshtml
GenderPayGap.WebUI/Views/Admin/ViewOrganisation.cshtml
GenderPayGap.WebUI/Views/Admin/ViewUser.cshtml
GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedback.cshtml
GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedbackRowsPartial.cshtml
GenderPayGap.WebUI/Views/Organisation/DisplayReportSection.cshtml
GenderPayGap.WebUI/Views/Register/ChooseOrganisation.cshtml
GenderPayGap.WebUI/Views/Register/SelectOrganisation.cshtml
GenderPayGap.WebUI/Views/Scope/CodeExpired.cshtml

I've tried to cover all <input>, <button> and <a> tags

AB#39895 ambiguous buttons

---

GenderPayGap.Core/Enums.cs
GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationReturnController.cs
GenderPayGap.WebUI/Models/Admin/AdminDeleteReturnViewModel.cs
GenderPayGap.WebUI/Views/Admin/ViewOrganisation.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationReturn/DeleteReturns.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturnDetails.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturns.cshtml

AB#40775 Admin delete submission

---

GenderPayGap.Core/Classes/ASearchRepository.cs
GenderPayGap.Core/Classes/AzureSearchRepository.cs
GenderPayGap.Core/Enums.cs
GenderPayGap.Core/Global.cs
GenderPayGap.Tests.Common/TestHelpers/SetupHelpers.cs
GenderPayGap.WebUI/Classes/Presentation/ViewingService.cs
GenderPayGap.WebUI/Startup.cs

Remove the use of the SearchLog CSV files.
We record searches in Google Analytics, so no longer need this

AB#40966 Remove Search log

---

GenderPayGap.Core/Enums.cs
GenderPayGap.Core/Global.cs
GenderPayGap.Tests.Common/TestHelpers/SetupHelpers.cs
GenderPayGap.WebJob/Program.cs
GenderPayGap.WebJob/Startup.cs
GenderPayGap.WebUI/Controllers/AdminController.cs
GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
GenderPayGap.WebUI/Startup.cs

Replace the "Bad SIC code" CSV log with normal logging.
I was thinking of setting up Azure alerts to email us about this, but it looks like this hasn't happened since April 2019, so it's probably not worth it.

AB#40965 Replace "Bad SIC code log" with normal logging

---

GenderPayGap.Extensions.AspNetCore/Extensions.Services.cs
GenderPayGap.IdentityServer4/Startup.cs
GenderPayGap.WebUI/Startup.cs

Remove all calls to IsDevelopment()

AB#41325 Remove calls to IsDevelopment()

---

GenderPayGap.WebUI/Views/Components/StepByStep/Step.cshtml
GenderPayGap.WebUI/Views/GovUkFrontend/GovUkFrontendLayout.cshtml
GenderPayGap.WebUI/Views/ReportingStepByStep/ReportingSteps.cshtml
GenderPayGap.WebUI/Views/ReportingStepByStep/StandalonePage.cshtml
GenderPayGap.WebUI/Views/Viewing/Launchpad/PrototypeIndex.cshtml
GenderPayGap.WebUI/wwwroot/styles/_gender-pay-gap-custom.scss
GenderPayGap.WebUI/wwwroot/styles/components/_section-break.scss
GenderPayGap.WebUI/wwwroot/styles/components/_step-by-step-navigation-gpg.scss
GenderPayGap.WebUI/wwwroot/styles/components/_warning.scss

Update prototype to match Claire's designs on Invision. Screenshots of the changes are posted in the ticket.

AB#42000 update signposting guidance

---

GenderPayGap.Core/Global.cs
GenderPayGap.Database/Models/AuditLog.cs
GenderPayGap.Database/Models/DataProtectionKey.cs
GenderPayGap.Database/Models/DraftReturn.cs
GenderPayGap.Database/Models/Feedback.cs
GenderPayGap.Database/Models/InactiveUserOrganisation.cs
GenderPayGap.Database/Models/Organisation.cs
GenderPayGap.Database/Models/OrganisationAddress.cs
GenderPayGap.Database/Models/OrganisationName.cs
GenderPayGap.Database/Models/OrganisationPublicSectorType.cs
GenderPayGap.Database/Models/OrganisationReference.cs
GenderPayGap.Database/Models/OrganisationScope.cs
GenderPayGap.Database/Models/OrganisationSicCode.cs
GenderPayGap.Database/Models/OrganisationStatus.cs
GenderPayGap.Database/Models/PublicSectorType.cs
GenderPayGap.Database/Models/ReminderEmail.cs
GenderPayGap.Database/Models/Return.cs
GenderPayGap.Database/Models/ReturnStatus.cs
GenderPayGap.Database/Models/SicCode.cs
GenderPayGap.Database/Models/SicSection.cs
GenderPayGap.Database/Models/User.cs
GenderPayGap.Database/Models/UserOrganisation.cs
GenderPayGap.Database/Models/UserStatus.cs
GenderPayGap.WebUI/Controllers/Admin/AdminDataMigrationController.cs

These are the changes needed to the Azure instance (to export the data)

GPG-215 Migrate database (changes for Azure)

---

GenderPayGap.Core/Classes/ErrorMessages/CustomErrorMessagesConfig.cs
GenderPayGap.Core/Global.cs
GenderPayGap.Database/Models/AuditLog.cs
GenderPayGap.WebUI/Controllers/Admin/AdminDataMigrationController.cs
GenderPayGap.WebUI/ExternalServices/DataRepositories/IDataRepository.cs
GenderPayGap.WebUI/ExternalServices/DataRepositories/SqlRepository.cs
GenderPayGap.WebUI/Models/Admin/AdminDataMigrationViewModel.cs
GenderPayGap.WebUI/Search/SearchCacheUpdaterService.cs
GenderPayGap.WebUI/Views/AdminDataMigration/DataMigrationFromFile.cshtml
GenderPayGap.WebUI/Views/AdminDataMigration/DataMigrationFromRemoteServer.cshtml

These are the changes needed to the PaaS instance (to import the data)

GPG-215 Migrate database (changes for PaaS)

---

GenderPayGap.WebUI/Views/Organisation/ManageOrganisation.cshtml

-  Change style of address in manage organisation page
- Searched for other gray color in the styles and css, to the extent I have spent time on seem ok

GPG-308 Accessibility - Low color contrast

---

GenderPayGap.Core/Enums.cs
GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationSectorController.cs
GenderPayGap.WebUI/Models/Admin/AdminChangeSectorViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminSectorHistoryViewModel.cs
GenderPayGap.WebUI/Services/AuditLogModels/AdminChangeSectorAuditLogDetails.cs
GenderPayGap.WebUI/Views/Admin/ViewOrganisation.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationSector/ChangeSector.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationSector/ConfirmSectorChange.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationSector/ViewOrganisationSector.cshtml

Updated branch to fix the git history from GPG-182-allow-admin-to-change-sector!

GPG-182 Allow Admin to Change Organisation Sector

---

GenderPayGap.WebUI/Views/StaticPages/AccessibilityStatement.cshtml

I also added a few carriage returns etc. so it was easier to see on my screen!

GPG-396 Content changes to Accessibility Statement

---

GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationFoundController.cs
GenderPayGap.WebUI/Search/AddOrganisationSearchService.cs
GenderPayGap.WebUI/Services/OrganisationService.cs

* Deleted orgs appear in search results
* Back button is sometimes broken

GPG-462 GPG-463 Add Organisation bugs

---

GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/AppSettings.UnitTests.json
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/ControllerBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/OrganisationBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/OrganisationScopeBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/UserBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/UserOrganisationBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Account/AccountCreationController/AccountCreationTests.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Administration/Scope/ScopeControllerTests.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Scope/ScopeControllerTests.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestHelpers/NewUiTestHelper.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestHelpers/UserHelper.cs
GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationScopeController.cs

Adds a unit test for scope retirement when a new scope is added, as well as builders for Users, Organisations, and OrganisationScopes.

GPG-410 Scope Change Testing

---

GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/OrganisationBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/UserBuilder.cs

@dulciejackson feel free to use this if you think it's useful - if not, feel free to ignore!

Auto-generate IDs for unit tests (in a thread-safe way)

---

README.md

Tiny, but I thought it might be nice to show the build pipeline status on the README!

Adds Azure Pipelines badge to README.md

---

GenderPayGap.WebUI/Views/StaticPages/AccessibilityStatement.cshtml

We recently received some accessibility testing feedback, so we need update the accessibility statement to reflect the results of this.

GPG-505 Updates accessibility statement copy

---

GenderPayGap.WebUI/Areas/Account/Views/ManageAccount/ManageAccount.cshtml
GenderPayGap.WebUI/Areas/Account/Views/Shared/AccountNavigation.cshtml
GenderPayGap.WebUI/Controllers/Account/ManageAccountController.cs
GenderPayGap.WebUI/Models/Account/ManageAccountViewModel.cs
GenderPayGap.WebUI/Views/Components/Navigation/AccountTabs.cshtml
GenderPayGap.WebUI/Views/Components/StatusMessages/StatusMessages.cshtml
GenderPayGap.WebUI/Views/Components/StatusMessages/StatusMessagesViewModel.cs
GenderPayGap.WebUI/Views/ManageAccount/ManageAccountNew.cshtml
GenderPayGap.WebUI/Views/ReportBonusPay/ReportBonusPay.cshtml
GenderPayGap.WebUI/Views/ReportDiscardDraft/ReportDiscardDraft.cshtml
GenderPayGap.WebUI/Views/ReportEmployeesByPayQuartile/ReportEmployeesByPayQuartile.cshtml
GenderPayGap.WebUI/Views/ReportHourlyPay/ReportHourlyPay.cshtml
GenderPayGap.WebUI/Views/ReportLinkToWebsite/ReportLinkToWebsite.cshtml
GenderPayGap.WebUI/Views/ReportOverview/ReportOverview.cshtml
GenderPayGap.WebUI/Views/ReportResponsiblePerson/ReportResponsiblePerson.cshtml
GenderPayGap.WebUI/Views/ReportReviewAndSubmit/ReportReview.cshtml
GenderPayGap.WebUI/Views/ReportSizeOfOrganisation/ReportSizeOfOrganisation.cshtml
GenderPayGap.WebUI/wwwroot/styles/_gender-pay-gap-custom.scss
GenderPayGap.WebUI/wwwroot/styles/components/_account-tabs.scss
GenderPayGap.WebUI/wwwroot/styles/components/_yesno.scss

All the links from this page have been updated to the new design system, so now this is being updated to the new design system (at last)!
After this is all reviewed I'll create a second PR to swap the links over to pointing at this page instead of the old version 😄

GPG-423 Update Manage Account Page

---

GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Builders/UserBuilder.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Account/ChangeEmailTests.cs
GenderPayGap.WebUI/Views/ChangeEmail/ChangeEmail.cshtml

The code for this was already done (woop woop) so I just added a few unit tests to make sure it all works ok 😄

GPG-418 Update Email Unit Tests

---

GenderPayGap.WebUI/Views/GOVUK/Layouts/template.cshtml
GenderPayGap.WebUI/Views/GovUkFrontend/GovUkFrontendLayout.cshtml

GPG-532 Fixes Admin Link Not Showing Bug

---

GenderPayGap.Database/Models/Extensions/OrganisationAddress.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/CodeQualityTests/DoNotAllowHtmlDotRawTests.cs
GenderPayGap.WebUI/Controllers/OrganisationController.cs
GenderPayGap.WebUI/Controllers/RegisterController.Request.cs
GenderPayGap.WebUI/Models/Organisation/RemoveOrganisationModel.cs
GenderPayGap.WebUI/Models/Register/OrganisationViewModel.cs
GenderPayGap.WebUI/Views/Admin/Search.cshtml
GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedbackRowsPartial.cshtml
GenderPayGap.WebUI/Views/ManageOrganisations/ManageOrganisation.cshtml
GenderPayGap.WebUI/Views/Organisation/ConfirmRemove.cshtml
GenderPayGap.WebUI/Views/Organisation/ManageOrganisation.cshtml
GenderPayGap.WebUI/Views/Register/ConfirmCancellation.cshtml
GenderPayGap.WebUI/Views/Register/ReviewAddress.cshtml
GenderPayGap.WebUI/Views/Register/ReviewRequest.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/BonusPay/BonusPaySection.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/HourlyRate/HourlyRateSection.cshtml
GenderPayGap.WebUI/Views/Viewing/Finder/Parts/Facets/Keywords.cshtml

Except in a few places where I couldn't quickly verify that it's not needed.
We can tackle these later

GPG-540 Stop using Html.Raw and create a unit test to check we're not using it

---

GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/CodeQualityTests/EnsureAllPostRequestsRequireAntiForgeryTokenTests.cs
GenderPayGap.WebUI/Controllers/Account/AccountCreationController.cs
GenderPayGap.WebUI/Controllers/Account/ChangeEmailController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminDataMigrationController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminFeedbackController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationCompanyNumberController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminReAddRetiredSubmissionsController.cs
GenderPayGap.WebUI/Controllers/Admin/AdminReferenceDataController.cs
GenderPayGap.WebUI/Controllers/CookieController.cs
GenderPayGap.WebUI/Controllers/SendFeedback/FeedbackController.cs
GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedbackRowsPartial.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationCompanyNumber/ChangeOrganisationCompanyNumber.cshtml
GenderPayGap.WebUI/Views/AdminOrganisationCompanyNumber/OfferChangeOrRemoveOrganisationCompanyNumber.cshtml
GenderPayGap.WebUI/Views/Components/CookieBanner.cshtml
GenderPayGap.WebUI/Views/Cookie/CookieSettings.cshtml
GenderPayGap.WebUI/Views/GOVUK/Layouts/template.cshtml

I've found a way to write a unit test to make sure all our POST requests must use the `[ValidateAntiForgeryToken]` attribute

GPG_546 Ensure all POST request contain a CSRF token (anti-forgery token)

---

GenderPayGap.WebUI/Controllers/OrganisationController.cs
GenderPayGap.WebUI/Models/Organisation/RemoveOrganisationModel.cs
GenderPayGap.WebUI/Views/Organisation/ConfirmRemove.cshtml
GenderPayGap.WebUI/Views/Organisation/RemoveOrganisationCompleted.cshtml

[GPG-531 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-531)
The new design system includes a bunch of accessibility fixes, so we want to upgrade these pages to ensure optimum accessibility for all users.
This PR just updates the UI to the new design system - not any of the controller code or view models.

GPG-531 Updates Remove User from Org page to new design system

---

GenderPayGap.WebUI/Views/Components/CovidMessage.cshtml

[GPG-537 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-537)
Updates the text in the coronavirus message to make it clear which reporting year is being referred to.

GPG-537 Updates copy of coronavirus message

---

Documentation/Load testing.md
Documentation/README.md
LoadTests/LoadTests.iml
LoadTests/README.md

In advance of running some load tests, I've started on some documentation on how to do that. There's also a document in Notion with more detailed plans for when and how we should run load tests, so this is really just the bare minimum technical stuff.
This isn't quite complete - I think we'll need a few changes to the Gatling script because it's a bit old and some of the controllers/pages have been reorganised since the scenario was recorded - but that's to follow.
Would appreciate any feedback on how useful these instructions are :D

GPG-552: document load test instructions

---

GenderPayGap.Core/Classes/Extensions.cs
GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/UpdatePublicFacingDownloadFilesJob.cs
GenderPayGap.WebUI/Controllers/Admin/AdminFeedbackController.cs
GenderPayGap.WebUI/Models/AdminReferenceData/ReferenceDataHelper.cs

Used reference [docs](https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration/Configuration/) to update CsvHelper config to include the SanitizeForInjection property, which appears to JustWork™️

GPG-571 Fixes malicious excel injection vulnerability

---

LoadTests/SET_UP_TEST_ENTITIES.sql

[GPG-606 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-606)
[GPG-619 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-619)
**Load Testing III: An Emergence of Syntax Errors**
Makes some more fixes to the reporting journey load tests, including rewriting the MySQL script for PostgreSQL so test database entities are set up correctly and can be used throughout the tests. More work to be done for refactoring the test to pass on the reporting steps, but I wanted to get the script reviewed before continuing!

GPG 606/619 Fixes more failing sections and migrates setup script to PostgreSQL

---

GenderPayGap.WebUI/Views/PrivacyPolicy/PrivacyPolicy.cshtml

[GPG-610 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-610)
Denise did a review of the privacy policy and noticed that there was a duplicate sentence - this PR just removes the second one as she asked.
Test: checked that removing sentence makes sense in context of other privacy policy text
Risk: very low
Documentation: none needed

GPG-610 Deletes duplicate sentence in privacy policy

---

GenderPayGap.WebUI/Helpers/DownloadHelper.cs

Specifies the date format as yyyy/MM/dd to output when creating csvs

GPG-657 Specify a date format when creating csvs

---

.gitignore
Infrastructure/gpg-ipdeny/README.md
Infrastructure/gpg-ipdeny/deploy.sh
Infrastructure/gpg-ipdeny/manifest.yml
Infrastructure/gpg-ipdeny/nginx.conf

Initial state of it, not ready to merge.

GPG-643 Add script to deploy IP denylist app

---

Documentation/Load testing.md
GenderPayGap.WebUI/Views/ManageOrganisations/OrganisationReportsTable.cshtml
Infrastructure/ConnectToPaas_DB_LoadTest.sh
Infrastructure/CreateEnvironment.sh
LoadTests/README.md
LoadTests/src/test/scala/default/RecordingSimulation.scala

A few updates to the load testing README, the CSS selectors used in the load test code, and an extra check to make sure the Manage Organisation page loads as expected.

GPG-603 Some final tweaks to load testing setup and documentation

---

Infrastructure/gpg-ipdeny/manifest.yml
Infrastructure/gpg-ipdeny/nginx.conf
LoadTests/SET_UP_TEST_ENTITIES.sql
LoadTests/src/test/scala/default/RecordingSimulation.scala

Fixes some final stuff for the load test, including adding the alternative reporting journey so both versions of the reporting journey (swapped with a feature flag) can be tested.

GPG-603 Adds alternative reporting journey

---

LoadTests/README.md

Added a bunch more context to the load test README from experience setting up infrastructure, db and configuring code.

GPG-682 Update load test README

---

GenderPayGap.WebUI/Views/AccountCreation/AlreadyCreatedAnAccountQuestion.cshtml
GenderPayGap.WebUI/Views/AccountCreation/CreateUserAccount.cshtml

We got some errors after rebase due to missing imports

GPG-NONE Fixed errors

---

GenderPayGap.WebUI/AzureAttachAutoscalingPolicy.sh
Infrastructure/gpg-ipdeny/AzureDeployIPDeny.sh

Pipeline error due to syntax error with the previous version, this fixes it

GPG-NONE Fix deployment scripts

---

Infrastructure/gpg-ipdeny/AzureDeployIPDeny.sh

Rewriting the Azure IP Deny script so that it will deploy to multiple environments properly.

Gpg none fix ip deny deploy

---

GenderPayGap.WebUI/Views/AdminOrganisationStatus/ViewOrganisationStatus.cshtml

https://technologyprogramme.atlassian.net/browse/GPG-683
Check if the organisation status has an user assigned. If not, display a blank cell.
All the AC passed locally

GPG-683 Fixed status history bug

---

GenderPayGap.WebUI/Views/Submit/OrganisationSize.cshtml
GenderPayGap.WebUI/Views/Submit/SubmissionComplete.cshtml

- Minor styling changes on the submission complete page
- There was an extra space on the organisation size page

GPG-652 Minor fixes

---

Documentation/Companies House Api.md
Documentation/README.md

Added documentation based on the investigation I did for GPG-701

Gpg 701 add companies house documentation

---

GenderPayGap.WebUI/Views/ChangeEmail/ChangeEmail.cshtml
GenderPayGap.WebUI/Views/Submit/CheckData.cshtml
GenderPayGap.WebUI/Views/Submit/EmployerWebsite.cshtml
GenderPayGap.WebUI/Views/Submit/EnterCalculations.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/BonusPay/BonusDiffText.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/BonusPay/BonusPaySection.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/HourlyRate/HourlyRateSection.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Quartiles/QuartilesSection.cshtml
GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Report.cshtml

Fixed issues:
- reporting pages breadcrumbs broken
- Related content not displayed at the bottom on mobile devices
- Capitalisation on Change email address breadcrumbs
- supporting narative text missing full stop
- buttons not aligned (IE)
- details not working (IE)
Tested:
- Chrome
- IE
- Mobile (using Dev tools)

GPG-NONE Content changes fixes

---

GenderPayGap.WebUI/Classes/BaseClasses/BaseController.cs
GenderPayGap.WebUI/Controllers/OrganisationController.cs
GenderPayGap.WebUI/Controllers/ScopeController.cs
GenderPayGap.WebUI/Views/Organisation/ScopeDeclared.cshtml

Fixes for the links on the scope declared confirmation page and redirect at the end of the set in scope journey.
All these scope changing views/actions are probably a bit more complicated than they need to be, might be worth considering re-working them in the future

GPG-651 Fixes for the Scope journeys

---

GenderPayGap.WebUI/GenderPayGap.WebUI.csproj

I had a look at the changelog and no major changes were made.
Tested: Released this build to the load test environment and the emails are sent successfully.

GPG-746 Bumped notify package version

---

GenderPayGap.WebUI/Views/Compare/CompareTableRows.cshtml

https://technologyprogramme.atlassian.net/browse/GPG-724
Redirect user to the employer page if the employer has not reported yet

GPG-724 Fixed comparison table broken link

---

GenderPayGap.WebUI/Controllers/Admin/AdminDatabaseIntegrityChecksController.cs
GenderPayGap.WebUI/Helpers/IntegrationChecksHelper.cs
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ActiveOrganisationsWithTheSameCompanyNumber.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ActiveOrganisationsWithTheSameName.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/DatabaseIntegrityChecks.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/DatabaseIntegrityChecksBreadcrumbs.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWhereLatestAddressIsNotActive.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveAddresses.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveReturnsForASingleYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithMultipleActiveScopesForASingleYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithNoActiveScopeForEveryYear.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/OrganisationsWithoutAnActiveAddress.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PrivateEmployersReturnsWithoutResponsiblePerson.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PrivateSectorOrganisationsWithAPublicSectorType.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/PublicSectorOrganisationsWithoutAPublicSectorType.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsTable.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithFiguresWithMoreThanOneDecimalPlace.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidBonusFigures.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidBonusFiguresGivenNoWomenBonus.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidBonusMeanMedianFigures.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidCompanyLink.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidMeanMedianFigures.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidQuartersFigures.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidTextFieldsValues.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithMissingFigures.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithQuartersFiguresSumDifferentThan100.cshtml

See https://technologyprogramme.atlassian.net/browse/GPG-735
- Added new integration checks
- Refactored existing views to use the breadcrumbs partial

GPG-735 Added database integrity checks for the submission form data

---

GenderPayGap.Core/App_Data/CustomErrorMessages.config

Changes from the final check through for missed changes from the custom error config content changes document. No idea which of these are actually used anywhere, perhaps a tech debt task is needed to clear up any that are unused.

GPG-654 Final error message content changes

---

GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/DatabaseIntegrityChecks.cshtml

GPG-756: Add subheading to DB Integrity checks page

---

GenderPayGap.Database/Models/Extensions/Organisation.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestHelpers/ViewingServiceHelper.cs
GenderPayGap.WebUI/BusinessLogic/Models/Compare/CompareReportModel.cs
GenderPayGap.WebUI/BusinessLogic/Services/OrganisationBusinessLogic.cs
GenderPayGap.WebUI/Content/gpg-govuk-table.css
GenderPayGap.WebUI/Views/Compare/CompareTableHeaders.cshtml
GenderPayGap.WebUI/Views/Compare/CompareTableRows.cshtml

See ticket [GPG-723](https://technologyprogramme.atlassian.net/browse/GPG-723)
Tests: AC passed locally

GPG-723 Added nature of business to comparison table

---

GenderPayGap.WebUI/BusinessLogic/Models/Submit/ReturnViewModel.cs
GenderPayGap.WebUI/Models/AccountCreation/CreateUserAccountViewModel.cs
GenderPayGap.WebUI/Models/AddOrganisation/AddOrganisationManualViewModel.cs
GenderPayGap.WebUI/Models/SendFeedback/FeedbackViewModel.cs

Please see the comments on [GPG-620](https://technologyprogramme.atlassian.net/browse/GPG-620)
Tested locally, no risks

GPG-620 Added character limit validation

---

GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Administration/AdminDatabaseIntegrityChecksControllerTests.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestHelpers/UiTestHelpers.cs
GenderPayGap.WebUI/Controllers/Admin/AdminDatabaseIntegrityChecksController.cs
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/DatabaseIntegrityChecks.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidOptedOutOfReportingPayQuartersValue.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithInvalidQuartersFigures.cshtml
GenderPayGap.WebUI/Views/AdminDatabaseIntegrityChecks/ReturnsWithMissingFigures.cshtml

https://technologyprogramme.atlassian.net/browse/GPG-796
Added tests + tested locally

GPG-796 database integrity checks

---

GenderPayGap.WebUI/Controllers/Account/AccountCreationController.cs
GenderPayGap.WebUI/Repositories/UserRepository.cs

**Testing:** Tested the create account and change email journeys - both of them work as expected. 
**Risks:** None
**Documentation:**
The investigation report is [here](https://technologyprogramme.atlassian.net/browse/GPG-708?focusedCommentId=71459)

GPG-708 Improve performance

---

GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml

GPG-815: Show notice on employer page if retired with submitted reports

---

GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs
GenderPayGap.WebUI/Controllers/EhrcController.cs

https://technologyprogramme.atlassian.net/browse/GPG-822

GPG-822 Make csv files accessible to EHRC

---

GenderPayGap.Core/Global.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Account/ChangePasswordControllerTests.cs
GenderPayGap.WebUI/BusinessLogic/Abstractions/IUserRepository.cs
GenderPayGap.WebUI/Controllers/Account/ChangePasswordController.cs
GenderPayGap.WebUI/Helpers/LoginHelper.cs
GenderPayGap.WebUI/Repositories/UserRepository.cs
GenderPayGap.WebUI/Views/Login/LoggedOut.cshtml

https://technologyprogramme.atlassian.net/browse/GPG-578
D: None
R: None
T: tested locally as well

GPG-578 change password improvements

---

GenderPayGap.WebUI/Controllers/RegisterController.Request.cs

See [this comment](https://technologyprogramme.atlassian.net/browse/GPG-810?focusedCommentId=75866)

GPG-810 Soft delete organisation if registration request is rejected

---

GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/SubmissionControllerTests.cs
GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Services/SubmissionServiceTests.cs
GenderPayGap.WebUI/BusinessLogic/Services/DraftFileBusinessLogic.cs
GenderPayGap.WebUI/Classes/Presentation/SubmissionService.cs
GenderPayGap.WebUI/Controllers/SubmitController.DraftConfirm.cs
GenderPayGap.WebUI/Controllers/SubmitController.cs

see ticket: https://technologyprogramme.atlassian.net/browse/GPG-805
The draft must be removed from the database if there are no changes saved.

GPG-805: Remove draft if no changes

---

Infrastructure/gpg-ipdeny/deploy.sh

The environment variable was not properly - it contained only an IP address.
Tested now:
```
echo $AWS_CLOUDFRONT_TRUSTED
set_real_ip_from 120.52.22.96/27; set_real_ip_from 205.251.249.0/24; set_real_ip_from 180.163.57.128/26; set_real_ip_from 204.246.168.0/22; set_real_ip_from 205.251.252.0/23; set_real_ip_from 54.192.0.0/16; set_real_ip_from 204.246.173.0/24; set_real_ip_from 54.230.200.0/21; set_real_ip_from 120.253.240.192/26; set_real_ip_from 116.129.226.128/26; set_real_ip_from 130.176.0.0/17; set_real_ip_from 108.156.0.0/14; set_real_ip_from 99.86.0.0/16; set_real_ip_from 205.251.200.0/21; set_real_ip_from 223.71.71.128/25; set_real_ip_from 13.32.0.0/15; set_real_ip_from 120.253.245.128/26; set_real_ip_from 13.224.0.0/14; set_real_ip_from 70.132.0.0/18; set_real_ip_from …
```

GPG-826: ipdeny app deploy script fix

---

GenderPayGap.WebUI/Views/AccountCreation/StartPagePrototype.cshtml
GenderPayGap.WebUI/Views/ActionHub/Pages/Effective.cshtml
GenderPayGap.WebUI/Views/ActionHub/Pages/MixedResult.cshtml
GenderPayGap.WebUI/Views/ActionHub/Pages/Overview.cshtml
GenderPayGap.WebUI/Views/ActionHub/Pages/Promising.cshtml
GenderPayGap.WebUI/Views/AddOrganisationManualConfirm/ManualConfirm.cshtml
GenderPayGap.WebUI/Views/Admin/Search.cshtml
GenderPayGap.WebUI/Views/Cookie/CookieSettings.cshtml
GenderPayGap.WebUI/Views/GovUkFrontend/GovUkFrontendLayout.cshtml
GenderPayGap.WebUI/package-lock.json
GenderPayGap.WebUI/package.json
GenderPayGap.WebUI/wwwroot/scripts/gov_uk_front_end.js
GovUkDesignSystem/GovUkDesignSystemComponents/Accordion.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/AccordionViewModel.cs
GovUkDesignSystem/GovUkDesignSystemComponents/Button.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/CharacterCount.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/ErrorMessage.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/Footer.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/Header.cshtml
GovUkDesignSystem/GovUkDesignSystemComponents/Hint.cshtml
GovUkDesignSystem/GovUkHtmlHelperExtensions.cs
package-lock.json

See ticket [GPG-830](https://technologyprogramme.atlassian.net/browse/GPG-830)
There were some breaking changes so we need to make some code changes as well.
All the breaking changes are listed [here](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md) and [here](https://github.com/sass/node-sass/releases).
Components affected:
* Accordion - the design has changed. Page: Actions to close the gap and Manual SIC codes
* Header
* Cookie banner
* Hints - Page: Admin search page
* Skip link
* Error messages
* Conditional check boxes - Page: Feedback page
* Characters count - Page: Feedback page
The designs should look the same apart from the accordions that use[ the new design](https://design-system.service.gov.uk/components/accordion/)
**Testing:**
Checked different journeys …

GPG-830: Bump npm modules

---

GenderPayGap.Core/Extensions/AspNetCore/MaintenancePageMiddleware.cs

Hi Malina,
I'm not sure if this works (I haven't been able to run it on my laptop - I don't have Postgres installed!), but this is the code I think we'd need to allow Maintenance Mode to work.

Ensure "Maintenance Mode" doesn't break Health Check

---

GenderPayGap.WebUI/Models/ManageOrganisations/ManageOrganisationViewModel.cs
GenderPayGap.WebUI/Services/DraftReturnService.cs

See ticket: https://technologyprogramme.atlassian.net/browse/GPG-840
Tested locally

GPG-840: Fix incorrect report status tag

---

GenderPayGap.Core/App_Data/CustomErrorMessages.config
GenderPayGap.WebUI/Views/AccountCreation/ConfirmationPage.cshtml

see details here: https://technologyprogramme.atlassian.net/browse/GPG-841

GPG-841: Fix email confirmation page

---

GenderPayGap.WebUI/Models/Report/ReportFiguresViewModel.cs
GenderPayGap.WebUI/Models/Report/ReportResponsiblePersonViewModel.cs
GovUkDesignSystem/Attributes/ValidationAttributes/GovUkValidateDecimalRangeAttribute.cs

https://technologyprogramme.atlassian.net/browse/GPG-848

GPG-848: Updated error messages for reporting journey

---

GenderPayGap.WebUI/Helpers/ReportFiguresHelper.cs

see the bug details [here](https://technologyprogramme.atlassian.net/browse/GPG-844)
Tested locally

GPG-844: Check if property has no errors before adding others

---

GenderPayGap.WebUI/Controllers/Report/ReportFiguresController.cs
GenderPayGap.WebUI/Controllers/Report/ReportResponsiblePersonController.cs
GenderPayGap.WebUI/Controllers/Report/ReportSizeOfOrganisationController.cs
GenderPayGap.WebUI/Models/Report/ReportFiguresViewModel.cs
GenderPayGap.WebUI/Models/Report/ReportResponsiblePersonViewModel.cs
GenderPayGap.WebUI/Models/Report/ReportSizeOfOrganisationViewModel.cs
GenderPayGap.WebUI/Views/ReportFigures/ReportFigures.cshtml
GenderPayGap.WebUI/Views/ReportResponsiblePerson/ReportResponsiblePerson.cshtml
GenderPayGap.WebUI/Views/ReportSizeOfOrganisation/ReportSizeOfOrganisation.cshtml

Figures -> Person responsible (if private) -> Org size -> Link to GPG info -> Report overview

GPG-845: Users are now redirected to the appropriate page when reporting

---

GenderPayGap.WebUI/Views/AccountCreation/CreateUserAccount.cshtml

"Error:" now added to page title based on `Model.HasAnyErrors();`

GPG-484: "Error:" added to title based on if the model has any errors.

---

.gitignore
terraform/main.tf
terraform/provider.tf
terraform/variables.tf

This creates the most barebones version of a multiple s3 remote back up I could, without resorting to new project directories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cabinetoffice/gender-pay-gap/458)

GPG-866: Configured terraform setup

---

GenderPayGap.WebUI/Models/Admin/AdminChangeCompaniesHouseOptInOutViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminChangePublicSectorClassificationViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminChangeScopeViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminChangeSectorViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminChangeStatusViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminDeleteReturnViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminOrganisationCompanyNumberViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminRemoveUserViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminResendVerificationEmailViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminReturnLateFlagViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminSicCodeUploadCheckViewModel.cs
GenderPayGap.WebUI/Models/Admin/AdminSicSectionUploadCheckViewModel.cs
GenderPayGap.WebUI/Models/Admin/ChangeOrganisationAddressViewModel.cs
GenderPayGap.WebUI/Models/Admin/ChangeOrganisationNameViewModel.cs
GenderPayGap.WebUI/Models/Admin/ChangeOrganisationSicCodesViewModel.cs
GenderPayGap.WebUI/Models/Admin/DeleteOrganisationNameViewModel.cs
GenderPayGap.WebUI/Models/AdminChangeUserContactPreferencesViewModel.cs
GenderPayGap.WebUI/Models/Register/OrganisationViewModel.cs
GenderPayGap.WebUI/Models/Scope/ScopeViewModel.cs
GenderPayGap.WebUI/Views/Scope/OutOfScopeQuestions.cshtml

Some issues occured after the merge. In particular, character count attributes needed the attribute name as an argument.

Gpg 460 merge fixes

---

.gitignore
terraform/aws-windows-deployment-manifest.json
terraform/dev-app.tfbackend
terraform/dev-app.tfvars
terraform/elasticbeanstalk.tf
terraform/main.tf
terraform/preprod-app.tfbackend
terraform/preprod-app.tfvars
terraform/prod-app.tfbackend
terraform/prod-app.tfvars
terraform/provider.tf
terraform/variables.tf
terraform/vpc.tf

This contains:
- The vpc and elastic beanstalk application
- The manifest json file  _NOTE: the Build Gender Pay Gap - AWS pipeline won't succeed until this is merged because it's necessary (along with the archive file) for azure devops to deploy elastic beanstalk_. 
- Environment specific backends
- Additional providers

Gpg 867 1 elastic beanstalk

---

terraform/dev-app.tfvars
terraform/preprod-app.tfvars
terraform/prod-app.tfvars
terraform/variables.tf
terraform/vpc.tf

Stripped down to most basic config - 1.34gb (slight downgrade from 1.5gb), single node, no failover.
Also making slight tweaks to variables.

Gpg 869 cache

---

terraform/elasticache.tf

Alter log destination in cluster resource

GPG: Alter log destination in cluster resource

---

terraform/dev-app.tfvars
terraform/preprod-app.tfvars
terraform/prod-app.tfvars

GPG: Upgrade ELB version

---

GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml

Removal of unnecessary component: There was 2 selects, one in C# one in JS. the C# one has been removed and the spacing has been fixed in the code.

GPG-909: unneeded select object removed, formatting cleanup.

---

terraform/elasticbeanstalk.tf

https://trello.com/c/5bjpCzNu/4230-spike-investigate-gpg-issues

4230: Change auto-scaling behaviour - CPU-based, rather than network-based

---

GenderPayGap.Core/Global.cs
GenderPayGap.WebUI/Models/Report/ReportSizeOfOrganisationViewModel.cs
GenderPayGap.WebUI/Views/AddOrganisationChooseSector/ChooseSector.cshtml
GenderPayGap.WebUI/Views/AddOrganisationManualChooseSector/ManualChooseSector.cshtml
GenderPayGap.WebUI/Views/Components/ReportOverview/ReportOverviewSections.cshtml
GenderPayGap.WebUI/Views/Organisation/DeclareScope.cshtml
GenderPayGap.WebUI/Views/ReportConfirmation/ReportConfirmation.cshtml
GenderPayGap.WebUI/Views/ReportFigures/ReportFigures.cshtml
GenderPayGap.WebUI/Views/ReportLinkToWebsite/ReportLinkToWebsite.cshtml
GenderPayGap.WebUI/Views/ReportOverview/ReportOverview.cshtml
GenderPayGap.WebUI/Views/ReportResponsiblePerson/ReportResponsiblePerson.cshtml
GenderPayGap.WebUI/Views/ReportSizeOfOrganisation/ReportSizeOfOrganisation.cshtml
GenderPayGap.WebUI/Views/ReportStarting/ReportStarting.cshtml
GenderPayGap.WebUI/Views/Scope/ConfirmScope.cshtml

https://trello.com/c/ijVfG3Jw/4278-update-content-in-the-gpg-service-1

4278: Content updates
