- GenderPayGap.IdentityServer4/Controllers/AccountController.cs
Make sure sign-out still works with Chrome's new cookie settings
> #38878 On logout, manually expire cookies

- GenderPayGap.WebUI/Models/Admin/AdminSearchViewModel.cs
- GenderPayGap.WebUI/Services/AdminSearchService.cs
- GenderPayGap.WebUI/Startup.cs
- GenderPayGap.WebUI/Views/Admin/Search.cshtml
The search functionality on the admin site is quite slow.
This will become quite irritating during the busy period as the Service Desk need to do lots of searches.
Currently, the search controller loads the full set of organisations and users for each search.
This change periodically loads this data into an efficient in-memory cache.
> #39257 Speed up Admin Search by caching Organisations and Users in memory

- GenderPayGap.WebUI/Controllers/AdminController.cs
On the Admin/Downloads page, there are two downloads for "User Consent" which match the two questions we ask during sign-up.
The descriptions of these two downloads are confusing.
I've updated them to reflect the questions that we ask the user when they register
> #39164 Change description on user consent admin download page to reflect actual question asked during registration

- GenderPayGap.Core/Classes/Logger/CustomLogger.cs
- GenderPayGap.WebJob/Functions/Functions.SendReminderEmails.cs
The function would start, successfully send the first email to me (valid email), then fall over on the second one which was an invalid email (Notify smoke test address). This would result in only a single result in the DB.
The problem was with our CustomLogger. I was passing a `User` object, which it then tried to convert to JSON, but it would go and get the associated `UserOrganisations` which would in turn go and get the `User`. This caused the program to hang. This also explains why in the Azure logs we would see the function start but never finish.
I've also taken this opportunity to remove some of the other logging and try/catch blocks. Hopefully making the code more readable.
> #37486 Fix SendReminderEmail Function

- GenderPayGap.Core/Enums.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationSectorController.cs
- GenderPayGap.WebUI/Models/Admin/AdminChangePublicSectorClassificationViewModel.cs
- GenderPayGap.WebUI/Views/Admin/ViewOrganisation.cshtml
- GenderPayGap.WebUI/Views/AdminOrganisationSector/ChangePublicSectorClassification.cshtml
- GovUkDesignSystem/GovUkHtmlHelperExtensions.cs
Public sector organisations have a Public Sector Type (classification)
e.g. NHS / University / Academy Trust...
All public sector organisations are supposed to have this but, for some, it's missing.
This allow the Service Desk to add / edit this classification
> #38815 Allow Service Desk to change an organisation's public sector type

- GenderPayGap.Core/Global.cs
- GenderPayGap.WebUI/Views/Shared/_Tracking.cshtml
- GenderPayGap.WebUI/appsettings.PROD.json
- GenderPayGap.WebUI/appsettings.json
We send Google Analytics data to GDS / Gov.UK
They have asked us to stop sending them data from our non-production environments.
This change fixes that problem.
> #39333 Stop sending Gov.UK/GDS our Google Analytics data from non-production environments

- GenderPayGap.WebUI/Views/ActionHub1/Effective.cshtml
- GenderPayGap.WebUI/Views/ActionHub1/MixedResult.cshtml
- GenderPayGap.WebUI/Views/ActionHub1/Overview.cshtml
- GenderPayGap.WebUI/Views/ActionHub1/Promising.cshtml
- GenderPayGap.WebUI/Views/ActionHub2/Hiring.cshtml
- GenderPayGap.WebUI/Views/ActionHub2/Leadership.cshtml
- GenderPayGap.WebUI/Views/ActionHub2/Overview.cshtml
- GenderPayGap.WebUI/Views/ActionHub2/Reading.cshtml
- GenderPayGap.WebUI/Views/ActionHub2/Talent.cshtml
- GenderPayGap.WebUI/Views/ActionHub2/Workplace.cshtml
- GenderPayGap.WebUI/Views/Compare/CompareEmployers.cshtml
- GenderPayGap.WebUI/Views/Organisation/ManageOrganisations.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Report.cshtml
- GenderPayGap.WebUI/Views/Viewing/Finder/SearchResults.cshtml
- GenderPayGap.WebUI/Views/Viewing/Launchpad/Index.cshtml
When the sitemap was removed it broke some of the old page titles and descriptions.
I looked up what the titles should be and added them directly to the cshtml files
> AB#39420 Fix page titles

- GenderPayGap.Database.Models/UserOrganisation.cs
- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/20200207093155_RemovePINHashFromUserOrganisation.Designer.cs
- GenderPayGap.Database/Migrations/20200207093155_RemovePINHashFromUserOrganisation.cs
- GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
- GenderPayGap.WebUI/Controllers/RegisterController.ServiceActivated.cs
- GenderPayGap.WebUI/Controllers/RegisterController.cs
More unused code (PINHash on UserOrganisation).
This was part of the Pin-in-the-Post process, but we now store an un-hashed PIN instead (in the PIN column)
> AB#38745 Remove unused PINHash property from UserOrganisation

- GenderPayGap.WebUI/Views/Register/OrganisationType.cshtml
Splits up the radio buttons on the select organisation type page. All but the first option mark the organisation as private. 
Previous version
New version
> AB#37500 Update view for selecting organisation

- GenderPayGap.WebUI/Views/Submit/EmployerWebsite.cshtml
Update the page for inputting a link to organisation's GPG report.
Previously it looked like this 
There is now an extra hint above the input and placeholder text to guide the user.
> #39077 Add hint and placeholder text

- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Models/Submit/SubmissionChangeSummaryTests.cs
- GenderPayGap.WebUI/Controllers/OrganisationController.cs
- GenderPayGap.WebUI/Models/Submit/SubmissionChangeSummary.cs
- GenderPayGap.WebUI/Views/Submit/LateWarning.cshtml
- Update late warning message
- Don't ask for late reason when changing SRO
- Don't show late warning for voluntary reports
Before:
After:
> AB#39251 improve understanding on late submission journey

- GenderPayGap.WebUI/Views/Register/OrganisationType.cshtml
The inset text grey bar wasn't showing in certain cases. We have now swapped to using the old GovUK Elements component instead.
> AB#37500 Swap to using old GovUK Elements component

- GenderPayGap.WebUI/Controllers/Admin/AdminDatabaseIntegrityChecksController.cs
I have swapped the IQueryables for Lists on the AdmibDatabaseIntegrityChecksController. 
On DEV we are seeing timeouts for the AJAX requests as they are taking over 30s. The hypothesis is that the sql is quick to run but our operations afterwards are what is exceeding the time limit. So by using Lists we hope to load everything in to memory at the beginning so we can close the DB connection before it times out.
I've tested this change locally but I really need to test it on DEV so I am going to self-approve this PR. @jamesgriff
> #39114 Swap IQueryables for Lists

- GenderPayGap.IdentityServer4/Views/Shared/_GovTemplate.cshtml
- GenderPayGap.IdentityServer4/Views/_ViewImports.cshtml
- GenderPayGap.WebUI/Views/GOVUK/Layouts/template.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Report.cshtml
- GenderPayGap.WebUI/Views/_ViewImports.cshtml
In Dev Tools, the HTML is looking a bit weird.
There's almost nothing in the <head> and the <body> starts with a few nested layers of "sitemap" stuff.
These changes should fix that
> Remove a few remaining SiteMap references

- GenderPayGap.Core/Enums.cs
- GenderPayGap.WebUI/Controllers/AdminController.cs
- GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedback.cshtml
- GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedbackRowsPartial.cshtml
- GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedbackRowsPartialViewModel.cs
Mark-ups from Hugh's testing:
* Rename "Uncategorised" to "New"
* In the "Spam" and "Not spam" sections, each feedback has a button to mark as "Spam" or "Not spam" - it's not necessary to have both!
> #38720 Feedback testing mark-ups

- GenderPayGap.WebUI/Models/Admin/AdminSearchViewModel.cs
- GenderPayGap.WebUI/Services/AdminSearchService.cs
- GenderPayGap.WebUI/Views/Admin/Search.cshtml
If we delete a user and they re-create their account, it becomes unclear which is which in the admin search.
This should make that a bit clearer.
If they are not active, we show "(Retired)" below their name
> #39493 Show user status in admin search (if the user is not active)

- GenderPayGap.WebJob/appsettings.json
Updates values from `[30, 7, 1]` to `[30, 7, 3]` in line with the original ticket.
Alongside this PR I will remove the env settings on PROD (currently set to `[30, 7, 3]`), so that it picks up the default settings.
This will also happen on TEST and PREPROD. 
DEV is already set to `[35, 12, 8]`
> #37486 Update ReminderEmailDays config value

- GenderPayGap.WebUI/Views/Register/OrganisationType.cshtml
These buttons were recently split out from 2 to 5. This change moves back to just two buttons, as the feedback was that it is more confusing to have 5. This change also adds more guidance around the choice.
The styling is taken from the [GDS Elements components](https://govuk-elements.herokuapp.com/form-elements/example-radios-checkboxes/) as this page still uses the old style.
This page is still being discussed on the ticket so might not yet be ready to go in.
**Before**
**After**
> #37500 Remove extra radio buttons and update copy

- GenderPayGap.WebJob/Functions/Functions.ExecuteWebJob.cs
- GenderPayGap.WebJob/Functions/Functions.MergeLogs.cs
- GenderPayGap.WebJob/Functions/Functions.StorageSnapshots.cs
I found another unrelated web job that can be deleted.
This one zips up log files (as a backup mechanism).
It's unnecessary because there's another web job that takes backups using an Azure mechanism.
> Remove another unnecessary webjob (duplicate storage backups)

- GenderPayGap.Core/FeatureFlagHelper.cs
- GenderPayGap.WebUI/appsettings.LOCAL.json
- GenderPayGap.WebUI/appsettings.json
Azure's configuration allows underscores, but the key vault doesn't. We should keep all app level config values in the key vault, so this change helps to bring things in line
> Remove underscore from feature flag config values

- GenderPayGap.WebUI/Views/Register/OrganisationSearch.cshtml
This change follows the advice given by DAC. It removes the visually hidden label and wraps the label in the h1. Following [this pattern](https://design-system.service.gov.uk/get-started/labels-legends-headings/). This change doesn't change the way the page looks.
I've also done a few searches for other visually hidden labels but didn't find anything. I only found this case with `<label.*class="visually-hidden">` and I also went through all cases of  `visually-hidden`. Let me know if you think there are any other searches I should be doing.
> AB#39796 Remove visually hidden label and wrap visible label in h1

- GenderPayGap.WebUI/Views/Shared/_SicCodeList.cshtml
Replace a table that was being used for layout purposes with nested lists. 
I have also checked through the codebase for other instances and couldn't find any other cases.
I checked all occurrences of `<li`. 
(ps. I also tried `<tr>\s*<td>\s*<li>` to look for the same pattern, and a negative lookback but I had less regex success with that one.)
Before 
After
> AB#39793 Swap table layout for nested lists

- GenderPayGap.WebJob/Functions/FrequentTimerTriggeredWebJobs/Functions.SendReminderEmails.cs
The reminder emails go to anyone tied to an organisation that is in scope or presumed in scope. But
it doesn't check whether the organisations are still active.
> AB#40164 Only include active organisations with active latest scopes

- GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturnDetails.cshtml
- GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturns.cshtml
- GenderPayGap.WebUI/wwwroot/styles/_gender-pay-gap-custom.scss
- GenderPayGap.WebUI/wwwroot/styles/pages/_admin-return-details-page.scss
* Swap two columns on the Returns page
* Highlight changes on the Return Details page
Looks like this:
> AB#38814 Improvements to Admin Return Details view in response to testing

- GenderPayGap.WebUI/Classes/BaseClasses/BaseController.cs
- GenderPayGap.WebUI/Controllers/RegisterController.cs
- I've put a feature flag around the block in BaseController. 
- For the `RequestPIN` action on line 262 of RegisterController, it is used in 2 views for requesting a new PIN (ActivateService.cshtml and RequestPIN.cshtml). With the new journey you should be unable to reach either of those pages, but in the `RequestPIN` action I have added an early return if the feature flag is on just in case, which redirects back to the manage organisations page.
----
From the ticket 
RegisterController.cs line 202
The "PINSent" action is the one we want to avoid calling.
If we do a Find Usages, we can see it's referred to in 4 places (+ extras in unit tests)
PINSent.cshtml
"Html.BeginForm()" - this doesn't actually do anything because there's no way to submit the form!
RegisterController.Organisation.cs …
> AB#40561 Add feature flag around PITP journeys

- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Account/CloseAccountController/CloseAccountTests.cs
- GenderPayGap.WebJob/Services/EmailSendingService.cs
- GenderPayGap.WebUI/Areas/Account/ViewServices/CloseAccountViewService.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminRemoveUserFromOrganisationController.cs
- GenderPayGap.WebUI/Controllers/AdminController.cs
- GenderPayGap.WebUI/Controllers/HomeController.cs
- GenderPayGap.WebUI/Controllers/OrganisationController.cs
- GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
- GenderPayGap.WebUI/Controllers/SubmitController.CheckData.cs
- GenderPayGap.WebUI/Controllers/SubmitController.cs
- GenderPayGap.WebUI/Controllers/ViewingController.cs
- GenderPayGap.WebUI/Services/EmailSendingService.cs
The reason for this ticket is to send GEO emails in test environments.
At the same time, I've done a couple of bits of refactoring, to make it easier to see where we use `Config.IsProduction`:
* Refactor repeated code in EmailSendingService
* Remove some unused logging which was based on `Config.IsProduction`
> AB#40962 Send GEO emails in test environments

- GenderPayGap.BusinessLogic/Services/UpdateFromCompaniesHouseService.cs
- GenderPayGap.Database.Models/Extensions/Organisation.cs
- GenderPayGap.Database.Models/OrganisationAddress.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationAddressController.cs
- GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
- GenderPayGap.WebUI/Services/PinInThePostService.cs
* LatestAddress - removed in yesterday's release
* OrganisationAddress.Status - this looks like it's being used for Pending addresses, but might be removed when we re-build the Add Organisation journey (so I've not change anything for now)
* Most recently created address - this is the one we want
* Most recently modified address - I've removed usages and marked it as obsolete
* GetAddress - removed all usages in this morning's release, now marked as obsolete
> AB#41224 Remove unclear addresses

- GenderPayGap.Core/Global.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/AppSettings.UnitTests.json
- GenderPayGap.WebJob/Functions/Functions.CheckSiteCert.cs
- GenderPayGap.WebJob/Services/EmailSendingService.cs
- GenderPayGap.WebUI/Areas/Account/ViewServices/CloseAccountViewService.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminRemoveUserFromOrganisationController.cs
- GenderPayGap.WebUI/Controllers/OrganisationController.cs
- GenderPayGap.WebUI/Controllers/RegisterController.Organisation.cs
- GenderPayGap.WebUI/Controllers/SubmitController.CheckData.cs
- GenderPayGap.WebUI/Services/EmailSendingService.cs
Two things related to the `GEODistributionList` setting:
* It should allow a list of email addresses, separated by `;`
* Since the GEO emails always go to the GEO DL, we don't need to pass the email address parameter in all the GEO emails
> #40576 GEODistricutionList needs to accept a list of email addresses, and is always the same, so can be simplified a bit

- GenderPayGap.WebUI/Controllers/Admin/AdminSearchController.cs
- GenderPayGap.WebUI/Models/Admin/AdminSearchViewModel.cs
- GenderPayGap.WebUI/Search/AdminSearchService.cs
- GenderPayGap.WebUI/Search/CachedObjects/SearchCachedOrganisation.cs
- GenderPayGap.WebUI/Search/CachedObjects/SearchCachedUser.cs
- GenderPayGap.WebUI/Search/CachedObjects/SearchReadyValue.cs
- GenderPayGap.WebUI/Search/SearchCacheUpdaterService.cs
- GenderPayGap.WebUI/Search/SearchRepository.cs
- GenderPayGap.WebUI/Search/WordSplittingRegex.cs
- GenderPayGap.WebUI/Services/AdminSearchService.cs
- GenderPayGap.WebUI/Startup.cs
- GenderPayGap.WebUI/Views/Admin/Search.cshtml
* Split out these bits from AdminSearchService
* SearchRepository
* SearchCacheUpdaterService
* 2 cached objects (for Organisations and Users)
* Keep AdminSearchService for the admin-specific search logic
* Make the Admin Search able to search by acronyms (e.g. "bbc" for "British Broadcasting Corporation Limited"
> AB#41007 Refactor Search

- GenderPayGap.WebUI/BusinessLogic/Services/UpdateFromCompaniesHouseService.cs
The `companiesHouseSicCodes` parameter was sometimes `null` (so I now check for null)
The other paramater, `sicCodes`, can't be null (as in, the way it's generated would result in an empty list)
> GPG-247 Fix CoHo opt-in null bug

- GenderPayGap.Database/Migrations/20200828111240_AddHasBeenAnonymisedToFeedbackTable.Designer.cs
- GenderPayGap.Database/Migrations/20200828111240_AddHasBeenAnonymisedToFeedbackTable.cs
- GenderPayGap.Database/Models/Feedback.cs
- GenderPayGap.WebUI/BackgroundJobs/BackgroundJobsApi.cs
- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/AnonymiseThreeYearOldFeedbackJob.cs
The new Data Retention Policy means that we should anonymise all PII after 3 years.
> As GEO I want to permanently delete all written feedback on the site three years after submission but keep scoring feedback so that the GPG team can monitor the performance of the site. 
- Creates db migration to add HasBeenAnonymised field to Feedback table
- Adds daily job to check for any un-anonymised Feedback which is over 3 years old
- Implements function in job to anonymise any PII to "supplied" and "not supplied" values depending on original data
> GPG-362 Anonymise Feedback

- GenderPayGap.WebUI/Controllers/HomeController.cs
- GenderPayGap.WebUI/Views/GOVUK/Layouts/template.cshtml
- GenderPayGap.WebUI/Views/GovUkFrontend/GovUkFrontendLayout.cshtml
- GenderPayGap.WebUI/Views/Home/AccessibilityStatement.cshtml
We need an accessibility statement in place by 23rd September to be compliant with legislation. An outline of what should be shown on the page can be found [in this Google doc](https://docs.google.com/document/d/1M2LdOu1QgSG9boBDKaE49JaCD-7B4Fdw2Z1EsqsSvBk/edit).
- Added 'Accessibility Statement' link to footer, as well as method in HomeController to navigate to it
- Added AccessibilityStatement.cshtml page with content as described in above Google doc
> GPG-396 Create Accessibility Statement Page

- GenderPayGap.WebUI/Views/AdminOrganisationSector/ViewOrganisationSector.cshtml
Jacob said that he'd prefer the sector history table to look more like address history:
> GPG-182 Rearranges the sector history table to look like AddressHistory

- GenderPayGap.WebUI/Views/AdminOrganisationSector/ViewOrganisationSector.cshtml
I tested this on dev and noticed a bug when there's only one sector change, so the Previous sectors header isn't added to the table and the subsequent initial sector line is misaligned:
I've fixed this here by adding a check for if the sectorChanges list has count 1 - and if so, I add the Previous sectors header.
I really should have caught this earlier - sorry 😕
> GPG-182 Adds single sector edge case

- GenderPayGap.sln
Building master has failed since d7d691285c5fa2aa33915c2438131353ac5939e3 due to duplicate Infrastructure and Documentation projects. I've renamed the folders so they display correctly but each pair now has a standard named parent project and a [Name]Nested project within it. 
Happy to change the naming to something else, but this fixes the collision!
> Fixes Duplicate Folder Names

- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Registration/RegisterControllerTests.Email.cs
- GenderPayGap.WebUI/Controllers/RegisterController.Request.cs
In test environments, "registration approved/rejected" emails are sent to the admin instead of the normal user.
This behaviour is very confusing and not needed (since we have different Notify API keys for test/live)
> GPG-529 Remove confusing email behaviour

- GenderPayGap.WebUI/Views/Viewing/Launchpad/Index.cshtml
Screen-readers rely on non-visible text to give more context about elements of the page so visually impaired users can navigate effectively. This link's non-visible text was missing explanation of it being a download, and the download size. 
Added "download" and PDF size to visually hidden text for clarification.
> GPG-465 Adds detail to download link

- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
On the page there are several separators to separate each section from each other instead of marking up the headings. Screen reader users rely on correct semantic mark-up to be able to identify information and relationships within the page.
Replaces `<span>`s with styled h3s
> GPG-468 Fixes screen-readability of public-facing employer report headers

- GenderPayGap.WebUI/Views/AddOrganisationSearch/Search.cshtml
Users who cannot perceive visually styling rely on correct semantic mark-up in order to identify information and relationships within the page. Currently the company name headings are marked up with a `<span>` rather than headings, which would make it hard for users of screen-readers to filter and efficiently navigate the page.
Replaced `<span>` with styled `<h3>` tags
> GPG-467 Fixes unmarked headings on add org page

- GenderPayGap.WebUI/Search/AutoCompleteSearchService.cs
- GenderPayGap.WebUI/wwwroot/scripts/accessible-autocomplete-gpg.js
[GPG-466 Jira Ticket](https://technologyprogramme.atlassian.net/browse/GPG-466)
DAC found that when you clicked an autocomplete item it navigated to a new page, which is an accessibility issue in particular for visually impaired users. They recommended replacing this with filling the search box with the search term and requiring either an enter press or clicking the search button to trigger the page change and show the search results. They also noted that clicking enter didn't work in the autocomplete.
After fixing the first issue, I noticed that it was possible to select an autocomplete item which then led to "0 results found" on the search page. This was because the search used for the autocomplete (all active orgs) wasn't the same as the search results (all active orgs that have ever …
> GPG-466 Fix Homepage Autocomplete

- GenderPayGap.WebUI/Views/ActionHub1/Promising.cshtml
[GPG-470 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-470)
[Link to the page on Dev](https://gender-pay-gap-dev.london.cloudapps.digital/actions-to-close-the-gap/promising-actions)
DAC noticed that one of the links on this page is a PDF, and whilst that's made clear to visually impaired users with visibly hidden text, it's not clear to sighted users that it's a PDF which opens in a new window. PDFs are notoriously inaccessible, which may be a problem for some sighted users as well as visually impaired users. DAC suggested making the document name, file type and "(opens in a new window)" text visible for everyone.
> GPG-470 Makes PDF opening in new window clearer to sighted users

- GenderPayGap.WebUI/Views/AccountCreation/CreateUserAccount.cshtml
If you have the full stop on the next line down, you automatically get a space between "sign in" and the full stop. But sticking them all on the same line stops that from happening
> Remove extra space on the Create Account page

- GenderPayGap.WebUI/Views/Viewing/Finder/Parts/Facets/OptionSelect.cshtml
[GPG-588 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-588)
Fixes the aria-labelling to give meaningful readout on screen-readers. Previously a screen-reader would read out e.g. "Size1 checkbox not checked" (giving no context to what that size might be) whereas now it reads out "Number of employees not provided checkbox not checked" or "500 to 999 employees checkbox not checked" which explains to the user what the checkbox is actually for 😄
> GPG-588 Fixes screen-reader readout of filter collapses

- GenderPayGap.WebUI/Views/Viewing/Finder/Parts/Facets/Keywords.cshtml
[GPG-476 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-476)
This nests the h1 text inside the legend instead so it's clearly linked to the form for visually impaired users, and doesn't cause a double readout of similar heading and legend.
A suggestion on this ticket was to remove the labels on radio buttons as these also cause a double readout. I don't think that's possible since they're used by sighted users to give context to a radio button - I tried adding `aria-hidden` to each label but that removes all context from the radio buttons, since the labels seem to implicitly give the radio buttons their `name` which is also read out by a screen reader, causing the duplication. Any suggestions appreciated!
> GPG-476 Stops double readouts of search options for screenreader users

- LoadTests/LoadTests.iml
- LoadTests/README.md
Just added a few bits and pieces to the load testing README - in particular, a section about setting up the Gatling recorder and getting it to record using the Windows proxy.
> Load test documentation updates

- LoadTests/src/test/scala/default/RecordingSimulation.scala
[GPG-605 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-605)
Adds the journey for a user to manually register a new organisation to the load testing scenario.
I didn't bother mocking unique addresses or SIC codes since I thought it wouldn't make a whole lot of difference if they're all identical (and it saves a loooot of time writing this code)!
> GPG-605 Adds manual registration journey to load tests

- GenderPayGap.WebUI/Views/StaticPages/AccessibilityStatement.cshtml
[GPG-617 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-617)
Updates the accessibility statement to reflect recent updates to the service.
I added the, "The following elements do not comply with accessibility regulations:" line to the copy myself, to match with the [guidelines](https://design-system.service.gov.uk/styles/typography/#lists) on the GOV.UK Design System about bullet lists requiring a lead-in line ending in a colon.
> GPG-617 Updates Accessibility Statement Copy

- GenderPayGap.WebUI/wwwroot/styles/components/_accessible-autocomplete.scss
- LoadTests/SET_UP_TEST_ENTITIES.sql
- LoadTests/src/test/scala/default/RecordingSimulation.scala
**Load Testing IV: The Fellowship of the Imports**
Updates the import of `accessible-autocomplete.min.css` in code.
`@import` in an SCSS file combines all imports into one file, whereas `@import` in a CSS file performs an HTTP request for each additional CSS file. This can be fixed by removing the `.css` chunk from the end of the import, which I've done here and fixes the 350+ failing requests in the load tests! We're now at 95% successful requests - I think there'll just need to be a final PR to fix the report submission journey 🎉 
Testing:
- Manually checked that updating the import still works as expected
- Ran the load tests after re-build and confirmed increase and successful requests
> GPG-606 Fixes accessible autocomplete import and requests

- LoadTests/SET_UP_TEST_ENTITIES.sql
- LoadTests/src/test/scala/default/RecordingSimulation.scala
The old change personal details journey was a single page, so those requests were failing now that the journey has been changed to multiple separate pages. This PR updates the load test scenario to navigate to the Manage Account page, then each sub-page and save some changes to the personal details. 
⚠️ Since this involves changing some personal/login details, the `SET_UP_TEST_ENTITIES` script now needs to be run against the db before each run of the load test scenario.
Test: 
- Ran the `SET_UP_TEST_ENTITIES` script against the db and made a few changes to avoid deletion errors
- Ran the load test scenario and saw the tests passing
Risk: very low
Documentation: clearly named each new step in the load tests so its purpose is clear for future dev work
> GPG-606 Adds new change personal details journey to scenario

- GenderPayGap.WebUI/Views/Components/TaskList/TaskList.cshtml
- GenderPayGap.WebUI/Views/Components/TaskList/TaskListViewModel.cs
- GenderPayGap.WebUI/Views/ReportOverview/ReportOverview.cshtml
- LoadTests/src/test/scala/default/RecordingSimulation.scala
[GPG-606 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-606)
The reporting journey has changed significantly over the past year - it used to be one long page, whereas now there is an overview page with 7 shorter form pages linked from it. This PR updates the load test code to follow the new reporting journey. Some minor changes have been made to `ReportOverview.cshtml` so elements can be selected and their hrefs saved in the load tests.
Testing: built project after changes with no errors, and ran load tests - all relevant requests pass, which means we're now at 99% passes!
Risk: very low
Documentation: clearly named new property `LoadTestId` on `TaskListItemViewModel`s so its function is clear for future maintenance
> GPG-606 Fixes full reporting journey

- GenderPayGap.WebUI/Views/Components/TaskList/TaskList.cshtml
- GenderPayGap.WebUI/Views/Components/TaskList/TaskListViewModel.cs
- GenderPayGap.WebUI/Views/ManageOrganisations/ManageOrganisations.cshtml
- GenderPayGap.WebUI/Views/ManageOrganisations/OrganisationReportsTable.cshtml
- GenderPayGap.WebUI/Views/ReportOverview/ReportOverview.cshtml
- GenderPayGap.WebUI/Views/Viewing/Finder/Parts/Results.cshtml
- LoadTests/LoadTests.iml
- LoadTests/SET_UP_TEST_ENTITIES.sql
- LoadTests/src/test/scala/default/RecordingSimulation.scala
[GPG-606 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-606)
Fixes `__RequestVerificationToken` chaining which sorts errors on search, sign in, privacy policy and initial reporting pages. Also updates regex checks on Manage Organisations, Manage Organisation and Report Overview pages - there's also a few changes to the non-load test code to add classes for css selectors.
I'll create a separate PR for the actual calculation pages - since last year the format has changed significantly, so I'd prefer to do it in two chunks than all here.
> GPG-606 Updates load test code for 2020/21 reporting year

- GenderPayGap.WebUI/Views/AdminOrganisationReturn/ViewReturns.cshtml
[GPG-598 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-598)
Smallest PR in the world - just changing the ordering so Returns are ordered by Status and then Modified date. Historically, the Modified date was also used to determine late flags, so the active Return could not be the first one shown - ordering by Status first ensures that this isn't the case.
Test: checked business logic with Raam, and checked with an old return that the rows now show in correct order
Risk: low
Documentation: none needed - the ordering is clear in the code and ordering by Status makes sense without need for further justification
> GPG-598 Orders returns by ReturnStatus

- GenderPayGap.WebUI/Startup.cs
Updated the AspNetCore.Session cookie to be HttpOnly and the AspNetCore.Antiforgery.xxxxx and AspNetCore.Cookies to have the Secure flag set.
cookie_settings and seen_cookie_message are left as before since the JS needs to interact with them. These show for me with HttpOnly false and Secure true running locally.
> GPG-583 Set HttpOnly and Secure on cookies

- GenderPayGap.Core/Extensions/Crypto.cs
- GenderPayGap.WebUI/Controllers/Account/PasswordResetController.cs
Changed the SendPasswordResetEmail method to use the Crypto.GetSalt method to produce a base64 string instead of Guid.NewGuid.
> GPG-573 Change password reset code to Crypto string

- GenderPayGap.WebUI/Views/Components/Navigation/AccountTabs.cshtml
This seems to be the correct setup for tabs after playing around with roles/labels in different places and a bit of googling. The presentation role to hide the list items from the reader and declaring the links as tabs.
> GPG-616 Change the Manage Account/Organisation aria roles to tabs

- GenderPayGap.WebUI/Helpers/NoCacheMiddleware.cs
- GenderPayGap.WebUI/Helpers/NoHtmlCachingMiddleware.cs
- GenderPayGap.WebUI/Startup.cs
Added middleware to set the Cache-Control header to no-cache for all pages. Css etc. still appear to be cached fine locally after this change. If we decide that we don't want to have the no-cache header for everything, this will probably have to be done differently, probably via ResponseCacheAttributes on the relevant controllers.
> GPG-581 Add middleware to add no-cache to headers

- GenderPayGap.WebUI/Views/Admin/ViewOrganisation.cshtml
Turns out it was that incorrect 'else if' statement I noticed on Friday that was causing an error when calling .Value on a nullable date since there is no PINConfirmedDate while the user is still pending
> GPG-624 Fix nullable object access error  in ViewOrganisation view

- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/CodeQualityTests/DoNotAllowHtmlDotRawTests.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/CodeQualityTests/DoNotUseRedirectWithReturnUrls.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/CompareControllerTests.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestHelpers/CodeQualityTestHelpers.cs
- GenderPayGap.WebUI/Controllers/CompareController.cs
- GenderPayGap.WebUI/Controllers/GoController.cs
- GenderPayGap.WebUI/Controllers/Login/LoginController.cs
- GenderPayGap.WebUI/Controllers/Report/ReportCompleteFinishAndSignOutController.cs
- GenderPayGap.WebUI/Controllers/SubmitController.DraftComplete.cs
- GenderPayGap.WebUI/Controllers/SubmitController.SubmissionComplete.cs
Updated calls that were Redirect(returnUrl) to LocalRedirect(returnUrl) and the corresponding unit tests.
return Redirect(url) and return new RedirectResult(url) look to be equivalent, so I've changed those using Redirect to return a RedirectResult to simplify the new unit test I've added that searches for instances of ' Redirect(' in the code (similarly to the Html.Raw one). This probably reduces code consistency overall, as we seem to mostly be using Controller methods in returns rather than returning new ActionResult objects, but they are all consistent with each other now i.e. all non-local Redirects are using return new RedirectResult. I did it this way as it makes the condition we are looking for in the new unit test simpler.
> Gpg 556 open url redirection

- GenderPayGap.WebUI/Views/ActionHub/Sections/Header.cshtml
Noticed an incorrect date when checking over GPG-629 on dev
> GPG-629 Correct date on Action to close the gap page

- GenderPayGap.WebUI/package-lock.json
- GenderPayGap.WebUI/package.json
Dependabot was reporting a conflicting dependency update. `yargs-parser` is a transitive dependency of `node-sass`, but there is a security vulnerability in the version of `yargs-parser` currently being used by our version of `node-sass`.
I've manually updated `node-sass`, which has allowed `yargs-parser` to be updated to a version with the security patch. Whilst I was at it, I updated a couple of other dependencies.
Testing: I've been through the site locally after these dependency changes were made, and everything I tried seems to work as I'd expect. We'll want to do some more thorough testing on dev to be completely sure before we release this.
Risk: moderate - we want to be totally sure that these upgrades don't deprecate any functionality we rely on. We should comprehensively test …
> Updates dependencies to fix dependabot conflict

- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/SendReminderEmailsJob.cs
[GPG-637 JIRA Ticket](https://technologyprogramme.atlassian.net/browse/GPG-637)
The reminder email Notify template uses a personalisation element called `OrganisationNames`, which is set in the code. There are 3 possible structures for this personalisation:
If there is only one Organisation:
- `OrganisationName`
If there are 2 Organisations:
- `OrganisationName1` and `OrganisationName2`
If there are n (where n > 2) Organisations:
- `OrganisationName1` and n-1 other organisations
Since we are now referring to "organisations" as "employers", this PR just updates the 3rd scenario to use consistent terminology.
**Testing:** updated notify email and used test functionality to send check email to testing gmail account.
**Risk:** reminder emails are only sent within the month before the …
> GPG-637 Updates text "organisations" to "employers" in Notify email personalisation

- SetEnvironmentVariablesInGovPaaS/Program.cs
After creating the new load testing environment and deploying to it, I noticed that the environment variables from the Azure pipelines don't appear to be being set on PaaS. It's not caused any problems recently because we haven't updated any of them, and they were already set on all the existing environments so the apps functioned as normal.
Since the new load test environment didn't have existing values of these environment variables, they weren't set at all and hence the app failed to connect to the database - the lack of the `ASPNETCORE_ENVIRONMENT` variable meant that the app didn't use TLS for the connection, assuming it was to a local db. After manually fixing that and successfully deploying, other elements of the app failed to work where an environment variable had not been …
> GPG-603 Updates command used to set environment variables

- Documentation/Accounts you will need to develop the service.md
- Documentation/Getting the code running.md
- Documentation/Software to install.md
- GenderPayGap.WebUI/Classes/Extensions/HtmlHelpers.cs
**Issue:** 
When there were multiple filters of the same type added (eg "sector") the query wasn't built correctly. It was `param=value1,value2` instead of `param=value1&param=value2`
I fixed this by converting the existing query to a `NameValueCollection` - the values will be handled separately.
Also updated the docs as part of this PR
> GPG-646 filters bug

- GenderPayGap.WebUI/Controllers/Account/AccountCreationController.cs
- GenderPayGap.WebUI/Models/AccountCreation/AlreadyCreatedAnAccountViewModel.cs
- GenderPayGap.WebUI/Models/AccountCreation/CreateUserAccountViewModel.cs
- GenderPayGap.WebUI/Views/AccountCreation/AlreadyCreatedAnAccountQuestion.cshtml
- GenderPayGap.WebUI/Views/AccountCreation/ConfirmEmailAddress.cshtml
- GenderPayGap.WebUI/Views/AccountCreation/ConfirmationPage.cshtml
- GenderPayGap.WebUI/Views/AccountCreation/CreateUserAccount.cshtml
- GenderPayGap.WebUI/Views/AccountCreation/UserNotFoundErrorPage.cshtml
- GenderPayGap.WebUI/Views/Login/Login.cshtml
Content changes and the new back/cancel buttons/links on the account creation screens.
I've gone through the site locally and made sure that the back/cancel links direct to the correct pages as expected when you are within the journey that starts at /already-created-an-account-question (linked from the Gov UK pages) or when you have accessed the create account page from an alternate route, e.g. the login page.
In the journey: 
- /already-created-an-account-question cancel links to the Gov UK StartUrl page (that links to it)
- /create-user-account back link takes you back to the /already-created-an-account-question page
- /create-user-account cancel links back to the Gov UK StartUrl page
Outside the journey:
- /create-user-account cancel links back to the ManageOrganisations endpoint …
> Gpg 631 create account content changes

- Infrastructure/gpg-ipdeny/autoscaling_policy_template.json
This is the threshold used on the load test environment.
A new instance is added if throughput is greater than 10rps for 60 seconds
As part of this ticket I also added a task to the[ Deploy to PaaS (push) group](https://dev.azure.com/govtequalitiesoffice/Gender%20Pay%20Gap/_taskgroup/b7fe281e-469b-4452-9be0-58a5f1db2e04) for attaching the policy to the main app.
> GPG=676 Updated threshold

- GenderPayGap.WebUI/Views/AccountCreation/AlreadyCreatedAnAccountQuestion.cshtml
- GenderPayGap.WebUI/Views/AccountCreation/ConfirmEmailAddress.cshtml
- GenderPayGap.WebUI/Views/AccountCreation/CreateUserAccount.cshtml
- GenderPayGap.WebUI/Views/Login/Login.cshtml
Changed all the right single quote marks I added in GPG-631. I can't really check it's definitely worked until it gets deployed to dev, since the right single quote marks render locally. Will just have to confirm they're correct when it's on dev.
I'll also quickly go through the other content pull requests I have and check there aren't any similar quote marks
> GPG-713 Fix right single quotes that don't render properly

- GenderPayGap.WebUI/manifest-gpg-dev.yml
- GenderPayGap.WebUI/manifest-gpg-loadtest.yml
- GenderPayGap.WebUI/manifest-gpg-preprod.yml
- GenderPayGap.WebUI/manifest-gpg-prod.yml
- GenderPayGap.WebUI/manifest-gpg-test.yml
Increased the timeout to 60s for all environments using the manifest files. [Cloud Foundry documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#timeout) says you can set it this way, but we may find out that it creates an error if it is bigger than cc.maximum_health_check_timeout (default 180) if our cloud foundry operator has overwritten that value to less than 60.
I've tested the environment manifest files deploy successfully for dev with the merging of the pull request for GPG-677, but won't be able to confirm this change has worked until this is merged and successfully updates the dev timeout (currently 1s)
> GPG-706 Change health check timeout to 60s for all envs

- GenderPayGap.WebUI/AzureAttachAutoscalingPolicy.sh
- GenderPayGap.WebUI/GenderPayGap.WebUI.csproj
- Infrastructure/gpg-ipdeny/AzureDeployIPDeny.sh
- Infrastructure/gpg-ipdeny/README.md
Updated the readme for the automated deployments of the IP deny app.
I've made changes to:
- the build all branches job to include and IP Deny Artifact
- the Deploy to PaaS (prepare) task group to include getting this new aritifact
- the Deploy to PaaS (push) task group to get the new secret file and deploy the IP Deny app
- Added a bunch of variables to the Deploy to PaaS/DEV release pipeline
Both the task groups are version 2.\*, so when we are ready to promote these to other environments, we should just need to add the new variables to the relevant releases and update the 2 task groups from version 1.\* to 2.*
I've also attempted to fix the automated deployment to dev when main is updated, which was broken by the change from main to master, but that may not have worked (the manually …
> GPG-680 Update IP Deny README with automated deployment details

- GenderPayGap.WebUI/BusinessLogic/Models/Submit/ReturnViewModel.cs
- GenderPayGap.WebUI/Controllers/SubmitController.EnterCalculations.cs
See ticket [GPG-729](https://technologyprogramme.atlassian.net/browse/GPG-729)
There were custom errors (not used) for this case.
```
<CustomErrorMessage code="2021" displayName="Enter the difference in mean bonus pay" title="There’s a problem with your data entry" description="Please enter your data" />
<CustomErrorMessage code="2023" displayName="Enter the difference in median bonus pay" title="There’s a problem with your data entry" description="Please enter your data" />
```
**Tested locally:**
- If % of men who receive bonus is 0 user is not allowed to enter bonus mean. An error is displayed
- If % of men who receive bonus is 0 user is not allowed to enter bonus median. An error is displayed
- If % of men is greater than 0 user cannot submit report without bonus mean. “Confirm and …
> GPG-729 Fixed bonus reporting bug

- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationChooseSectorController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationConfirmationController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationFoundController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationManualAddressController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationManualChooseSectorController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationManualConfirmController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationManualNameController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationManualSicCodesController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationRedirectsController.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationSearchController.cs
- GenderPayGap.WebUI/Models/AddOrganisation/AddOrganisationChooseSectorViewModel.cs
- GenderPayGap.WebUI/Models/AddOrganisation/AddOrganisationFoundViewModel.cs
- GenderPayGap.WebUI/Models/AddOrganisation/AddOrganisationManualViewModel.cs
- GenderPayGap.WebUI/Models/AddOrganisation/AddOrganisationSector.cs
- GenderPayGap.WebUI/Views/AddOrganisationChooseSector/ChooseSector.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationConfirmation/Confirmation.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationFound/AlreadyRegistering.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationFound/Found.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationManualAddress/ManualAddress.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationManualChooseSector/ManualChooseSector.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationManualConfirm/ManualConfirm.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationManualName/ManualName.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationManualSicCodes/ManualSicCodes.cshtml
- GenderPayGap.WebUI/Views/AddOrganisationSearch/Search.cshtml
- GenderPayGap.WebUI/Views/Components/Navigation/AccountTabs.cshtml
- GenderPayGap.WebUI/Views/ManageOrganisations/ManageOrganisations.cshtml
- GenderPayGap.WebUI/wwwroot/robots.txt
Content changes for the Add Employer journey. As part of this work I've also changed the routes from /add-organisation/ to /add-employer/ for all of these pages. This means that we have a new controller containing all the redirects for the old urls, in case they were bookmarked or linked from somewhere external for example (unlikely since it is all in the account protected area).
I've gone through the journey a few times and it all seems fine, and I didn't find anywhere that was linking to these pages with a none generated link, so everything should be fine.
> GPG-632 Content and route changes for Add Employer

- GenderPayGap.Core/App_Data/CustomErrorMessages.config
- GenderPayGap.WebUI/Controllers/Account/ChangeEmailController.cs
- GenderPayGap.WebUI/Views/ChangeEmail/ChangeEmail.cshtml
- GenderPayGap.WebUI/Views/ChangeEmail/ChangeEmailComplete.cshtml
- GenderPayGap.WebUI/Views/ChangeEmail/PleaseVerifyNewEmailAddress.cshtml
Content changes for the Manage Account pages. There were also a few areas that weren't included in the pdf document that I have updated in line with those that were (Organisation to Employer)
Only a few changes here, all wording. I've checked that they appear as expected. Note that the change for the Manage Organisation tab to Manage Employer has been done in GPG-632.
> Gpg 650 manage account content changes

- GenderPayGap.WebUI/BusinessLogic/Models/Submit/ReturnViewModel.cs
- GenderPayGap.WebUI/Classes/Extensions/HtmlHelpers.cs
Ticket [GPG-728](https://technologyprogramme.atlassian.net/browse/GPG-728)
The decimals were truncated to 1 decimal place because we applied the format string in both display and edit mode.
Even if we removed this, the decimals would be truncated to 2 decimal places in edit mode because this is the [default behaviour](https://github.com/aspnet/AspNetWebStack/blob/42991b3d2537b702736463f76a10a4fcf2ea44c9/src/System.Web.Mvc/Html/DefaultEditorTemplates.cs#L110).
As a workaround, we can use the "String" editor template. By doing this, on error, the user input is displayed and not a rounded value. User is still not able to submit the form if a figure has more than 1 decimal place. When displayed (on the review report page) the figures have a decimal place as before.
> GPG-728 Fixed decimals rounded in edit mode issue

- GenderPayGap.Core/Enums.cs
- GenderPayGap.WebUI/Services/OrganisationService.cs
Agreed that we should always just be re-activating the employer where it exists since the case where there are deleted/retired employers with submissions is only for retired employers which appear in the search to be able to select anyway.
There will be no issues with displaying the incorrect data in this case, as either the employer will have no submission data, or it will be one of these searchable retired employers perhaps with some data that would still be relevant since it is the same employer. Agreed that the process for manual deletion should also mark the submissions as retired where necessary, so we should never be in the case where incorrect data will appear.
Tested adding a few employers in various statuses to my local account and it either works as before, or successfully …
> GPG-716 Allow a user to add a retired employer

- GenderPayGap.WebUI/Views/AddOrganisationChooseSector/ChooseSector.cshtml
- GenderPayGap.WebUI/Views/Organisation/DeclareScope.cshtml
- GenderPayGap.WebUI/Views/Organisation/RemoveOrganisationCompleted.cshtml
- GenderPayGap.WebUI/Views/Organisation/ScopeDeclared.cshtml
- GenderPayGap.WebUI/Views/Scope/FinishOutOfScopeJourney.cshtml
Content change fixes for:
ChooseSector.cshtml h1 text 'What type of employer do you want to add?'
No bullets + "more options" should be removed (remove user)
Scope confirmation header font
"Was your employer required to report for the 2019/20 reporting year?" to XXXX-XX
Declare scope confirmation via newly created organisations being broken (it was using a different layout page)
Also swapped a couple of places I noticed where the reporting year helper wasn't used
Checked these ones in Chome/Firefox (none were browser specific errors)
> GPG-NONE Content change fixes

- GenderPayGap.WebUI/BusinessLogic/Services/UpdateFromCompaniesHouseService.cs
Companies with no organisation addresses were not fully updated (i.e. the initial address couldn't be added) by the FetchCompaniesHouseData job.
> GPG-NONE Add initial organisation address

- GenderPayGap.Core/Helpers/ReportingYearsHelper.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/CompareControllerTests.cs
- GenderPayGap.WebUI/Controllers/CompareController.cs
Changed the default year on the comparison table to the most recent “completed” year (i.e. its deadline has passed)
> GPG-722 Changed comparison table default year

- GenderPayGap.WebUI/BusinessLogic/Services/OrganisationBusinessLogic.cs
Changed the results from the compare to sort by the passed in list of encrypted organisation IDs by default so that they are sorted in the order that they are added to the comparison basket rather than by the numeric organisation IDs from the database.
> GPG-721 Default order by order added to comparison basket

- Infrastructure/gpg-ipdeny/nginx.conf
This issue was caused by the combination of the IP Deny app and cookies being accepted on a given environment.
If a user has accepted cookies, then the add to compare button attempts to set a cookie containing the compare string using the set-cookie header.
By default the nginx IP Deny app has a proxy_buffer_size of 4KB, which if the upstream app attempts to return greater than this amount in the headers, then it throws a 502 Bad Gateway. With 443 employers being added to the compare, the total response headers size is around 5.5KB.
Increased the value to 8KB to avoid this issue, this should be sufficiently large given the maximum that can be put in the compare is 500.
Tested by deploying this branch to the loadtest environment as we currently aren't using it, I can successfully get back …
> GPG-719 Update proxy_pass_buffer size

- GenderPayGap.WebUI/Controllers/RegisterController.cs
Added a permanent redirect (301) from the old /register/about-you address to the new /create-user-account address used to start the account creation process.
> GPG-742 Add redirect from old /register/about-you link

- GenderPayGap.WebUI/wwwroot/robots.txt
GPG-744: Added the SEMrush user agents to the robots.txt file
GPG-584: 
- Went through and removed the disallowed endpoints that are behind authorisation and a couple that no longer exist.
- /register/ is still there as I've just added the /Register/about-you endpoint to redirect to the new create account page in GPG-742.
- The remaining disallowed endpoints under /viewing/ are all the ones that relate to functionality like the add to compare buttons etc. that should probably remain disallowed as they aren't actual pages. Added a couple of extra ones I found in the viewing controller that weren't previously included in the list of disallowed endpoints, but probably should have been as they fall into the same category.
I think this is still the correct approach to take in terms of …
> Gpg 744 updating robots.txt

- GenderPayGap.Core/Extensions/DateRoutines.cs
- GenderPayGap.WebUI/Views/Compare/YearTabs.cshtml
- GenderPayGap.WebUI/Views/Scope/ConfirmScope.cshtml
- GenderPayGap.WebUI/Views/Scope/OutOfScopeQuestions.cshtml
- GenderPayGap.WebUI/Views/Submit/DraftComplete.cshtml
T - I've tested one of the changes by doing the following: go the homepage, click "search and compare" in the navbar", add a few employers for comparison, click "view comparison" check that the tab titles have the right date format e.g. 2019/2020. This tests the changes to the YearTabs.cshtml file. I'm not sure how to test the changes ConfirmScope.cshtml, OutOfScopeQuestions.cshtml and DraftComplete.cshtml.
R - There might be a few places missing. I haven't tested three of the changed files, there might be issues there.
D - none
> GPG-538: use FormatYearAsReportingPeriod accross the codebase.

- GenderPayGap.WebUI/Models/Search/SearchViewModel.cs
- GenderPayGap.WebUI/Scripts/Application/LiveSearch.js
- GenderPayGap.WebUI/Views/Shared/_Tracking.cshtml
- GenderPayGap.WebUI/Views/Viewing/Finder/Parts/Filter.cshtml
- GenderPayGap.WebUI/Views/Viewing/Finder/SearchResults.cshtml
T - I've used the Google Analytics Debugger Chrome extension to check if the event were being sent and their properties and it all look good.
R - Low risk, since it doesn't affect the user. 
D - I'll add a page on Swiki about the GA setup.
> Gpg 738 set up ga tracking for filters

- GenderPayGap.Core/Helpers/ReportingYearsHelper.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Services/Submission/IsCurrentSnapshotYearTests.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Services/Submission/IsHistoricSnapshotYearTests.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Services/SubmissionServiceTests.cs
- GenderPayGap.WebUI/Classes/Presentation/SubmissionService.cs
- GenderPayGap.WebUI/Controllers/OrganisationController.cs
**Issue:**
After removing 2020 from `ReportingStartYearsToExcludeFromLateFlagEnforcement` reports were marked as late (even though the deadline for 2020 was in October)
**Fix:**
Updated the late reports logic: check whether the deadline has already passed or not.
I've already tested this on the load test environment. [Here](https://technologyprogramme.atlassian.net/browse/GPG-712) are all the things that I've checked.
> GPG-712 Late submission fix

- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/SendReminderEmailsJob.cs
**Issue:** Only the latest reporting year (2021) was considered when sending the reminder emails.
**Fix:** Select all the reporting years that have upcoming deadlines.
I've also added a filter for the anonymised users.
I tested this on the load test environment and emails are sent. You can see an example [here](https://technologyprogramme.atlassian.net/browse/GPG-711?focusedCommentId=66418).
> GPG-711 reminder email fixes

- GenderPayGap.WebUI/Views/Shared/_Tracking.cshtml
We need to check if GA has been initialised before trying to send an event. Error:
```
Uncaught ReferenceError: ga is not defined
at sendGpgEvent (search-results?t=1&search=&orderBy=relevance:85)
at n.sendFilterEventToGA (application.min.js?v=915E15zCJnZebMOgwW5cwgDSh_VB5EeEmuhHD-28_Kg:1)
at n.updateResults (application.min.js?v=915E15zCJnZebMOgwW5cwgDSh_VB5EeEmuhHD-28_Kg:1)
at n.formChange (application.min.js?v=915E15zCJnZebMOgwW5cwgDSh_VB5EeEmuhHD-28_Kg:1)
at HTMLFormElement.dispatch (jquery-1.11.3.min.js:2)
at HTMLFormElement.v.handle (jquery-1.11.3.min.js:2)
```
> GPG-738 Check if GA has been initialised before sending event

- GenderPayGap.WebUI/Views/Shared/_Tracking.cshtml
I might have had the cookies accepted when I tested this on Friday 🤦 (lesson: do not create PRs on Friday evening 😁) 
The variable isn't defined so we need to check its type. Otherwise, we get the same error
> GPG-738 Fix

- GenderPayGap.WebUI/Views/Viewing/Finder/SearchResults.cshtml
T - Went to the viewing page. Checked that the filters were expandable. Selected a few filters, and checked that the counter under the filter group title were udpated.
R - Very low. This is code that already existed but had been wrongly removed (by me 😅)
D - no need.
> GPG-771: fix non expandable filters bug.

- Infrastructure/gpg-metrics/gpg-prometheus/manifest.yml
We've got the high disk utilisation alerts again...
As I expected, we could safely decrease the retention time as we don't use the in memory database but an external one.
Added the command I've run to [this documentation](https://technologyprogramme.atlassian.net/wiki/spaces/GPGS/pages/1437696070/Metrics)
**Note:** This has already been deployed. The app is working as expected.
> GPG-752 prometheus app update

- GenderPayGap.Core/Models/DownloadResult.cs
- GenderPayGap.Database/Models/Extensions/Return.cs
- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/UpdatePublicFacingDownloadFilesJob.cs
This covers [GPG-760](https://technologyprogramme.atlassian.net/browse/GPG-766), which is to add the organisation ID to the CSV file in order to allow researchers to link an organisation over time.
T - Deployed on Dev and did the following: 
1. Logged in as an admin. 
2. Opened [hangfire](https://gender-pay-gap-dev.london.cloudapps.digital/admin/hangfire) 
3. Triggered the UPDATE_PUBLIC_FACING_DOWNLOAD_FILES_JOB. 
4. Went to [downloads page](https://gender-pay-gap-dev.london.cloudapps.digital/viewing/download) 
5. Downloaded all the csv files. 
6. Checked that the second column on each file is titled "EmployerId" 
7. Checked that the employer ids were present and were as expected 
8. Clicked "Search and compare" in the header 
9. Selected a few companies for comparison 
10. Went to the …
> GPG-766: add employer id to csv

- GenderPayGap.WebUI/Content/Site.css
- GenderPayGap.WebUI/Views/Viewing/Finder/Parts/Facets/OptionSelect.cshtml
T- I went to /viewing/search-results?t=1&search=&orderBy=relevance and checked that the filter titles don't appear twice. I also tested with NVA screen reader and it read the filter titles correctly.
R- Very low risks. Maybe we should remove the legend, since it might be unnecessary.
D- No need.
> GPG-761: remove duplicate filter title

- GenderPayGap.Core/Extensions/VirtualDateTime.cs
- GenderPayGap.WebUI/Controllers/SendFeedback/FeedbackController.cs
- GenderPayGap.WebUI/Services/AuditLogger.cs
- GenderPayGap.WebUI/manifest-gpg-dev.yml
- GenderPayGap.WebUI/manifest-gpg-loadtest.yml
- GenderPayGap.WebUI/manifest-gpg-preprod.yml
- GenderPayGap.WebUI/manifest-gpg-prod.yml
- GenderPayGap.WebUI/manifest-gpg-test.yml
The majority of the database tables contain a column for the created date. None of the dates contain the timezone.
`VirtualDateTime.Now` uses the system timezone - As this bug hasn't been reported until now, the system timezone must have been "Europe/London" initially. However, now the system timezone is "UTC".
As we can't consider all of the dates (from the db) to be in UTC format, we should change the system timezone. Added an environment variable for setting this.
We use `VirtualDateTime.Now` for all the entries apart from the audit logs and the feedback ones, for these the default value is now() that uses the database timezone. 
We should use "VirtualDateTime.Now" everywhere for consistency.
**Tests:** I deployed this build to the dev environment to test the manifest file change and …
> GPG-751 Fixed incorrect date bug

- GenderPayGap.Core/Classes/Extensions.cs
- GenderPayGap.Core/Helpers/CsvWriter.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/CoreTests/Helpers/CsvWriterTests.cs
- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/UpdatePublicFacingDownloadFilesJob.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminFeedbackController.cs
- GenderPayGap.WebUI/Helpers/DownloadHelper.cs
See ticket [GPG-768](https://technologyprogramme.atlassian.net/browse/GPG-768)
We have the following CSV files:
- Admin downloads
- Admin feedback download
- Comparison results
- Public facing files
I excluded '-' from the injection characters as the injection function cannot be configured by us. However, we can add a custom type converter. Here all the values that start with '-' and are not decimals (we have only decimal figures) are prepended with a tab.
All the CSV files should be sanitized. Therefore, I added a custom `CsvWriter` and used it everywhere.
Added tests. Apart from that I've also checked the AC pass for all the files apart from the public facing ones locally. The public facing files are built by a background job - we don't run them locally. I will make sure I'll test this …
> GPG-752 Fixed csv negative values bug

- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/AppSettings.UnitTests.json
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/DatabaseTests/Return/ReturnTests.IsLateSubmission.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestsCommon/TestHelpers/ReturnHelper.cs
- GenderPayGap.WebUI/appsettings.LOCAL.json
See ticket [GPG-770](https://technologyprogramme.atlassian.net/browse/GPG-770)
I checked all the AC on the dev environment.
We already have tests for these. I added one test that was missing - check if the report is marked as late if the reporting year is excluded from late flag enforcement.
> GPG-770 Added test for reporting year excluded from late flag enforcement

- GenderPayGap.Core/Models/DownloadResult.cs
- GenderPayGap.Database/Models/Extensions/Return.cs
[GPG-776](https://technologyprogramme.atlassian.net/browse/GPG-776), to add the organisation postcode to the CSV files.
T - Deployed on Dev and did the following:
Logged in as an admin.
Opened hangfire
Triggered the UPDATE_PUBLIC_FACING_DOWNLOAD_FILES_JOB.
Went to downloads page
Downloaded all the csv files.
Checked that the fourth column on each file is titled "PostCode"
Checked that the postcodes were present and were as expected
Clicked "Search and compare" in the header
Selected a few companies for comparison
Went to the compare page
Clicked "Download data (CSV)"
Checked that the CSV does not contain the PostCode column.
R - Very low risk.
D - not necessary.
> GPG-776: add postcode to CSV files.

- GenderPayGap.WebUI/package-lock.json
Both of these dependencies are used by `node-sass`.  `node-sass` accepts `hosted-git-info` >= 2.1.4 and `lodash` >= 4.17.15
There is no risk - I had a look at the changelogs and the changes aren't breaking.
Tested locally, `node-sass` works as expected, the css files being compiled
> GPG-767 Bump vulnerable dependencies

- GenderPayGap.WebUI/Views/Submit/LateReason.cshtml
See ticket [GPG-783](https://technologyprogramme.atlassian.net/browse/GPG-783)
The reporting year was incorrect because the reporting start date (that is used for building that string) was not passed when submitting the late reason and the year for the default value was 1.
> GPG-783 Fixed invalid reporting year for late submissions bug

- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/BonusPay/BonusDiffText.cshtml
See ticket [GPG-790](https://technologyprogramme.atlassian.net/browse/GPG-790)
"mean" was duplicated because we displayed both "mean" and `Model.Statistic`.
We should use `Model.Statistic` instead of hardcoding "mean".
Tested locally.
> GPG-790 Fix bonus pay gap description typo

- Infrastructure/gpg-ipdeny/README.md
- Infrastructure/gpg-ipdeny/nginx.conf
Limit requests made to the app to 50 requests per second per IP Address
Risks:
People who use scripts to access the site and pull large amounts of data could be negatively affected e.g. their requests could timeout, or just take longer than it might have usually taken before
Potential DDOS attacks could circumvent this limit by just using lots of IP Addresses at once 
Testing:
Using the "hey" package, I make several requests to the loadtest environment, some exceeding the rate limit while others stayed under
**100 Requests, 10 concurrent workers, 10 Queries per second**
``` 
Summary:
 Total:       1.2774 secs
 Slowest:     0.3603 secs
 Fastest:     0.0154 secs
 Average:     0.0626 secs
 Requests/sec: 78.2833
...
Status code distribution:
 [200] 40 responses
 [503] 60 responses
```
**80 …
> GPG-773: Add rate limitng

- Infrastructure/gpg-ipdeny/README.md
- Infrastructure/gpg-ipdeny/nginx.conf
Add a burst queue of 100 requests
T: Clearing cache and loading up the loadtest site shows no 503s are thrown under normal loads
R: There could be someone trying to scrape data from the service doing a lot of requests that might exceed the burst queue (Low risk as the app wasn't designed for this)
D: In the README
> GPG-773: Add burst and nodelay

- GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationAddressController.cs
- GenderPayGap.WebUI/Models/Admin/ChangeOrganisationAddressViewModel.cs
- GenderPayGap.WebUI/Views/AdminOrganisationAddress/ConfirmAddressChange.cshtml
See ticket [GPG-808](https://technologyprogramme.atlassian.net/browse/GPG-808) - details about the bug in comments.
Testing:
* Tested locally. Once the employer has an address, the user can add it to their account and report successfully
Risk: None
Documentation: Not required
> GPG-808 Admin can add new address if none

- GenderPayGap.Core/Helpers/ReportingYearsHelper.cs
The check for showing the late submission warning was checking for the deadline day, not for the day after
> GPG-NONE: Fix Late submission warning showing up on deadline day

- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Models/Extensions/Organisation.cs
- GenderPayGap.Database/Models/Extensions/OrganisationAddress.cs
- GenderPayGap.Database/Models/Extensions/Return.cs
- GenderPayGap.Database/Models/OrganisationAddress.cs
- GenderPayGap.WebUI/BusinessLogic/Services/UpdateFromCompaniesHouseService.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationFoundController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs
- GenderPayGap.WebUI/Controllers/RegisterController.Request.cs
- GenderPayGap.WebUI/Models/Admin/ChangeOrganisationAddressViewModel.cs
- GenderPayGap.WebUI/Services/PinInThePostService.cs
- GenderPayGap.WebUI/Views/AdminOrganisationAddress/ConfirmAddressChange.cshtml
- GenderPayGap.WebUI/Views/AdminOrganisationAddress/OfferNewCompaniesHouseAddress.cshtml
Test
Went onto the employer details page and manage org page to make sure the postcode was in all caps. When this is deployed to dev we will be testing the downloaded CSVs
Risk
Since the Postcode automatic getter is still public devs in the future could access it that way, however, this is necessary for setting up entity framework
Docs
N/A
> GPG-779: Return all postcodes in all caps

- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/SubmissionControllerTests.cs
- GenderPayGap.WebUI/Classes/Presentation/SubmissionService.cs
- GenderPayGap.WebUI/Controllers/SubmitController.CheckData.cs
- GenderPayGap.WebUI/ErrorHandling/CustomErrorPageExceptions.cs
- GenderPayGap.WebUI/Views/Errors/ReportAlreadySubmitted.cshtml
One way to reproduce this bug is to have multiple sessions open at a given time. When the second report is submitted a error message should be displayed informing the user the report has already been submitted.
> GPG-818 Check report hasn't already been submitted

- Infrastructure/gpg-ipdeny/deploy.sh
- Infrastructure/gpg-ipdeny/nginx.conf
We found out the nginx app didn't work in Prod when checking if the EHRC endpoints were IP protected. Turned out the app was not configured correctly (as in it didn't work with a cdn routed domain)
You can see the gov.uk PaaS support reply here: https://technologyprogramme.atlassian.net/browse/GPG-826
Tested the configuration on the load test environment
> GPG-826: Trust AWS Cloudfront IP ranges

- GenderPayGap.Database/Models/Extensions/Organisation.cs
See details: https://technologyprogramme.atlassian.net/browse/GPG-842
When the sector of an organisation is changed all the accounting dates in the database are updated (for all the returns and scopes). This issue is caused by the following: the sector of an organisation was updated without updating the accounting date as well.
When fetching the return from the database we should compare the years of the accounting dates.
> GPG-842: Get return by reporting year

- GenderPayGap.WebUI/Services/EmailSendingService.cs
We removed the expire details from the confirmation email template as the links don't expire.
Updated email:
> GPG-847: Removed expire date info from the confirmation email

- GenderPayGap.WebUI/Views/Compare/YearTabs.cshtml
This ticket fixes an issue where the aria-selected labels were either not showing or not responding to the currently selected year.
This also fixes an issue where the role was not set to "tab" which caused screen readers to display each of the tab links as "links" they now show as selected and unselected tabs (as seen in the attached screenshots).
> GPG-473-tabs-on-compare: aria-selected and role added

- GenderPayGap.WebUI/Views/Compare/ComparisonBasket.cshtml
**Change made:**
- The role of the message that shows how many companies you have in your comparison bin is changed from "status" to "alert" which causes the screen reader to read out how many we are comparing and gives the user immediate feedback.
> GPG-475: Comparison list changes changed to role="alert".

- GenderPayGap.WebUI/Content/site.charts.css
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Quartiles/QuartilesBarChart.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Quartiles/QuartilesSection.cshtml
- Transparent border added to bar charts(both horizontal and vertical) this displays their outline on high contrast mode only.
- Transparent border added to keys "Women, Men", this displays their outline on high contrast mode only.
- Bar chart keys "Women, Men" hidden from screen-reader : they keys are irrelevant to screen readers as the data given by the bar charts is already given in text form without a colour key.
> GPG-472: Bar charts & keys have outline, screen reader ignore keys.

- GenderPayGap.WebUI/Views/AdminFeedback/ViewFeedbackRowsPartial.cshtml
The nature of this ticket was moving the details of a feedback submission to the top of the list for to speed up the rate at which admins can determine if a feedback submission is spam or not.
**Initially the details section was at the bottom:**
**Now the details are at the top of the list.**
> GPG-864: "details" moved to top of list and styling changed to match.

- GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs
- GenderPayGap.WebUI/Controllers/EhrcController.cs
- GenderPayGap.WebUI/Views/AdminDownloads/Downloads.cshtml
**Changes:**
Additional heading and downloads on the `admin./downloads` page.
The additional downloads are duplicates of the the 3 above however 4 new columns are added to the CSV: first name, second name, email address and date/time of the last user to log in who is associated with a given organisation.
These new documents have a different file name when downloaded.
> GPG-99: CSV Generation, controllers and front end changes.

- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
**Overview:**
The purpose of this ticket is to add a filter that allows users to see a only a specific years details and then return to seeing all years with a "show all option".
This is to be done using a `<Select>`  element and is to only be visible to users with JavaScript enabled on their browsers.
This is to be visible on both mobile and desktop(covered in 2 tickets).
**Changes:**
- reorganisation, text removal and restructuring of area above the years (as per the Figma designs - https://www.figma.com/file/vPKrhKrWG6z762gFgYgkvR/GPG-Dev-Handover?node-id=108%3A120).
- Select, hint and label elements created and appended to div via javascript.
- Hidden <input> passes year options as json where they are picked up by the js and used to create options.
- Options are then compared with …
> Gpg 909/910 add js filter

- GenderPayGap.Core/Helpers/ReportingYearsHelper.cs
- GenderPayGap.WebUI/Models/ManageOrganisations/ManageOrganisationViewModel.cs
- GenderPayGap.WebUI/Views/ManageOrganisations/ManageOrganisation.cshtml
- GenderPayGap.WebUI/Views/ManageOrganisations/OrganisationReportsTable.cshtml
- GenderPayGap.WebUI/Views/ManageOrganisations/UsersRegisteredToReportForOrganisation.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
This page is for users who are logged in and are associated with a company. This gives them a sort of dashboard where they can move onto other actions such as completing a report, editing an old report or viewing all reports.
-  There was one large table which held info for every reporting year on one page, we now have 2 tables, 1) latest due report, 2) missing reports.
- Company registered address moved to bottom of the page and styled as per the rest of the page.
- Link to view all reports page created (though not linked up yet).
Note: I moved the "registered users" table over to using a design library component as I had to make a visual change to it and saw an opportunity to improve the maintainability of the code.
> Gpg 759 manage reports page

- GenderPayGap.WebUI/Controllers/ManageOrganisations/ManageOrganisationsController.cs
- GenderPayGap.WebUI/Models/ManageOrganisations/AllOrganisationReportsViewModel.cs
- GenderPayGap.WebUI/Models/Shared/ReportStatusBadgeViewModel.cs
- GenderPayGap.WebUI/Views/ManageOrganisations/AllOrganisationReports.cshtml
- GenderPayGap.WebUI/Views/ManageOrganisations/AllOrganisationReportsTable.cshtml
- GenderPayGap.WebUI/Views/ManageOrganisations/ManageOrganisation.cshtml
- GenderPayGap.WebUI/Views/Shared/_ReportStatusBadge.cshtml
- GenderPayGap.WebUI/Views/Viewing/EmployerDetails/Employer.cshtml
This ticket is concerned with the creation of a new "all reports" page, the idea being the that previous page covered in GPG-759 shows a "dashboard" of actionable reports whereas the the "all reports" page shows all previous reports including the unactionable ones and serves as an archive, this includes pagination and yearly filtering.
Image showing the design for desktop- 
Image showing my implementation on desktop
Note: a change was agreed with the designer that we could reuse badges seen on the viewing pages, this is why the report status badges look different or are worded differently.
Image showing mobile design - 
Image showing mobile implementation - 
Note: a design change was agreed where the "draft report" button was moved below the badge so as to match the government design …
> Gpg 916 all reports page

- GenderPayGap.WebUI/Views/ReportFigures/ReportFigures.cshtml
- GenderPayGap.WebUI/Views/ReportStarting/ReportStarting.cshtml
- GenderPayGap.WebUI/wwwroot/styles/_gender-pay-gap-custom.scss
- GenderPayGap.WebUI/wwwroot/styles/components/_inset-text.scss
This ticket is concerned with changing styling and content of the reporting gender pay difference page.
**The main noteworthy changes:**
- "Step 2 of 5" above Heading.
- The difference is moved to the top
- Inset text used.
- Back used instead of breadcrumbs
- The difference between hourly pay and bonus pay is more clearly defined.
- Generally less text.
The design 
The implemented version
The old design
> GPG-920: styling and content changed to match new designs. Links changed

- GenderPayGap.WebUI/Views/Components/ReportOverview/ReportOverviewSections.cshtml
- GenderPayGap.WebUI/Views/Login/Login.cshtml
**Note:** I've checked all the other `<hr>` tags in the code.
All the other `<hr>` tags have semantic meaning, so don't need the `aria-hidden="true"` attribute.
> 4212: Accessibility: Remove unwanted HR, and mark a decorative HR as aria-hidden

- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/20230523165523_Remove UserOrganisation.Address.Designer.cs
- GenderPayGap.Database/Migrations/20230523165523_Remove UserOrganisation.Address.cs
- GenderPayGap.Database/Models/InactiveUserOrganisation.cs
- GenderPayGap.Database/Models/OrganisationAddress.cs
- GenderPayGap.Database/Models/UserOrganisation.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Administration/AdminDatabaseIntegrityChecksControllerTests.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/Controllers/Administration/AdminUnconfirmedPinsControllerTests.cs
- GenderPayGap.WebUI/Controllers/AddOrganisation/AddOrganisationEnterPinController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationStatusController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminPendingRegistrationsController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminUserStatusController.cs
- GenderPayGap.WebUI/Repositories/RegistrationRepository.cs
- GenderPayGap.WebUI/Views/AdminPendingRegistrations/Sections/PendingRegistrationsForOrganisationType.cshtml
`UserOrganisation` currently has a foreign key to `OrganisationAddress`.
**Why?**
Currently, **both** `Organisation` and `UserOrganisation` have foreign keys to `OrganisationAddress`.
`OrganisationAddress` conceptually belongs to `Organisation`, not to `UserOrganisation`.
`UserOrganisation` has a foreign key to `Organisation`.
and `Organisation` has a foreign key to `OrganisationAddress`.
so it's easy to navigate from `UserOrganisation` to an `OrganisationAddress`, without needing a direct link (which can get out of date).
> 4415: Remove unused code: UserOrganisation.Address

- GenderPayGap.Database/Migrations/20230524111230_Remove UserOrganisation.Modified.Designer.cs
- GenderPayGap.Database/Migrations/20230524111230_Remove UserOrganisation.Modified.cs
- GenderPayGap.Database/Models/InactiveUserOrganisation.cs
- GenderPayGap.Database/Models/UserOrganisation.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationStatusController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminPendingRegistrationsController.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminUserStatusController.cs
- GenderPayGap.WebUI/Views/AdminPendingRegistrations/Sections/PendingRegistrationsForOrganisationType.cshtml
The `UserOrganisation` table has a `Created` field and a `Modified` field.
We are removing the `Modified` field and just keeping the `Created` field.
**Why?**
The `Modified` field has not been kept up-to-date correctly.
Also, it is being used inconsistently (i.e. mainly to see when a row was created).
We keep other dates on the row for significant events, so there's no need to have a general `Modified` date.
> 4415: Remove unused code: UserOrganisation.Modified

- GenderPayGap.Database/Migrations/20230524114756_Remove Organisation.Modified.Designer.cs
- GenderPayGap.Database/Migrations/20230524114756_Remove Organisation.Modified.cs
- GenderPayGap.Database/Models/Organisation.cs
The `Organisation` table has a `Created` field and a `Modified` field.
We are removing the `Modified` field and just keeping the `Created` field.
**Why?**
The `Modified` field has not been kept up-to-date correctly.
It is never used in any code across the application
> 4415: Remove unused code: Organisation.Modified

- GenderPayGap.Database/Migrations/20230524115208_Remove Return.Created.Designer.cs
- GenderPayGap.Database/Migrations/20230524115208_Remove Return.Created.cs
- GenderPayGap.Database/Models/Extensions/Organisation.cs
- GenderPayGap.Database/Models/Return.cs
- GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/TestsCommon/TestHelpers/ReturnHelper.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminDownloadsController.cs
The `Return` table has a `Created` field and a `Modified` field.
We are removing the `Created` field and just keeping the `Modified` field.
**Why?**
Both fields are used for the same purpose, but the `Modified` field is used much more than the `Created` date.
We don't keep the two dates up to date consistently, so it's confusing to have both.
> 4415: Remove unused code: Return.Created

- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/20230524120155_Remove OrganisationScope.CampaignId.Designer.cs
- GenderPayGap.Database/Migrations/20230524120155_Remove OrganisationScope.CampaignId.cs
- GenderPayGap.Database/Models/OrganisationScope.cs
The `OrganisationScope` table has a field `CampaignId`.
**Why?**
It's never written or read in any code at all and hasn't been for a long time.
> 4415: Remove unused code: OrganisationScope.CampaignId

- GenderPayGap.Core/Enums.cs
- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/20230524120630_Remove OrganisationScope.RegisterStatus and RegisterStatusDate.Designer.cs
- GenderPayGap.Database/Migrations/20230524120630_Remove OrganisationScope.RegisterStatus and RegisterStatusDate.cs
- GenderPayGap.Database/Models/OrganisationScope.cs
The `OrganisationScope` table has fields `RegisterStatus` and `RegisterStatusDate`.
**Why?**
They are never written or read in any code at all and haven't been for a long time.
There is another date on `OrganisationScope` to keep track of when the row was created.
> 4415: Remove unused code: OrganisationScope.RegisterStatus/RegisterStatusDate

- GenderPayGap.Database/Migrations/20230524151344_Remove Organisation.DateOfCessation.Designer.cs
- GenderPayGap.Database/Migrations/20230524151344_Remove Organisation.DateOfCessation.cs
- GenderPayGap.Database/Models/Organisation.cs
- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/PurgeOrganisationsJob.cs
The `Organisation` table has a field `DateOfCessation`.
**Why?**
It's never written or read in any code (except a single log message) and hasn't been for a long time.
> 4415: Remove unused code: Organisation.DateOfCessation

- GenderPayGap.Database/Migrations/20230524151748_Remove OrganisationAddress.CreatedByUserId.Designer.cs
- GenderPayGap.Database/Migrations/20230524151748_Remove OrganisationAddress.CreatedByUserId.cs
- GenderPayGap.Database/Models/OrganisationAddress.cs
- GenderPayGap.WebUI/BackgroundJobs/ScheduledJobs/PurgeOrganisationsJob.cs
- GenderPayGap.WebUI/Services/OrganisationService.cs
The `OrganisationAddress` table has a field `CreatedByUserId`.
**Why?**
The Address is normally now created by the system, pulling the data in from Companies House.
We don't display or use the "created by user" anywhere in the code, except one place where it's unnecessary.
> 4415: Remove unused code: OrganisationAddress.CreatedByUserId

- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/20230524152018_Remove OrganisationPublicSectorType.Retired.Designer.cs
- GenderPayGap.Database/Migrations/20230524152018_Remove OrganisationPublicSectorType.Retired.cs
- GenderPayGap.Database/Models/OrganisationPublicSectorType.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminOrganisationSectorController.cs
The `OrganisationPublicSectorType` table has a field `Retired`.
**Why?**
On each `Organisation` there is a link to the latest `OrganisationPublicSectorType`.
We store a history of `OrganisationPublicSectorType` for each `Organisation`.
We store the `Created` date, so we can use this to sort the rows if needed, and the property `Organisation.LatestPublicSectorType` means it is easy to navigate directly to the active row, without needing a `Retired` property.
The `Retired` property isn't used anywhere in the code, apart from maintaining its own state.
> 4415: Remove unused code: OrganisationPublicSectorType.Retired

- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/GpgDatabaseContextModelSnapshot.cs
- GenderPayGap.Database/Models/OrganisationPublicSectorType.cs
The `OrganisationPublicSectorType` C# class has an Entity Framework navigation property `Organisations`.
**Why?**
This property is misleading.
Each `OrganisationPublicSectorType` only has 1 `Organisation`, not multiple.
Also, we never use this navigation property in any code.
> 4415: Remove unused code: OrganisationPublicSectorType.Organisations

- GenderPayGap.Database/GpgDatabaseContext.OnModelCreating.cs
- GenderPayGap.Database/Migrations/20230524153611_Remove PublicSectorType.Created.Designer.cs
- GenderPayGap.Database/Migrations/20230524153611_Remove PublicSectorType.Created.cs
- GenderPayGap.Database/Models/PublicSectorType.cs
The `PublicSectorType` table has a column `Created`.
**Why?**
All rows were created at the same time, so this date is not helpful.
This property is not used by any code.
> 4415: Remove unused code: PublicSectorType.Created

- GenderPayGap.WebUI/Models/AddOrganisation/AddOrganisationSearchViewModel.cs
- GenderPayGap.WebUI/Search/AddOrganisationSearchService.cs
- GenderPayGap.WebUI/Views/AddOrganisationSearch/Search.cshtml
- GenderPayGap.WebUI/Views/AdminPendingRegistrations/Sections/PendingRegistrationSimilarOrganisation.cshtml
In an earlier PR, I removed the unused `OrganisationReference` table.
This allows us to simplify some code.
The SearchService has a class `OrganisationIdentifier` which allows multiple identifiers for each organisation.
In reality, there is is now only ever one identifier that we use in this context: CompanyNumber.
So we can simplify the code to reflect this.
> 4415: Remove unused code: relating to OrganisationReference

- GenderPayGap.Core/Enums.cs
- GenderPayGap.Database/Migrations/20230525132055_Add User.UserRole.Designer.cs
- GenderPayGap.Database/Migrations/20230525132055_Add User.UserRole.cs
- GenderPayGap.Database/Models/User.cs
- GenderPayGap.WebUI/Controllers/Admin/AdminManageAdminUsersController.cs
At the moment, admin users are managed via a config setting.
This PR changes that to use a database column.
This PR contains a database migration + data migration.
After this has been run, there is another PR after this which will allow admins to manage other admin users etc.
> 4411: Manage admin users (part 1 of 2)

- terraform/elasticbeanstalk.tf
**What is this about?**
Replace `VCAP_SERVICES` environment variable with non-Gov.UK-PaaS-specific environment variables  
**What is this code?**
This PR contains Terraform changes to remove the old `VCAP_SERVICES` environment variable.
The previous PR contained the C# code changes.
> 4415: Remove unused code: Remove VCAP_SERVICES from terraform code
